import type { AppCreatorTabProps } from "./AppCreatorTab";
import type { AppAiTabProps } from "./AppAiTab";
import type { AppUploadTabProps } from "./AppUploadTab";
import type { AppEditorTabProps } from "./AppEditorTab";
import type { AppSettingsTabProps } from "./AppSettingsTab";
import type { AppStatusTabProps } from "./AppStatusTab";
import type { AppTimelineTabProps } from "./AppTimelineTab";
import type { AppMusicTabPanelProps } from "./AppMusicTabPanel";
import type { AppHomeTabProps } from "./AppHomeTab";
import type { AppWorkflowTabProps } from "./AppWorkflowTab";
import type { AppTerminalTabProps } from "./AppTerminalTab";

import type { AppTab } from "./appTabs";
import type {
  ConfigData,
  MusicFile,
  OutputVideo,
  VideoQualityReport,
  WorkspaceStatus,
} from "./appTypes";
import type { ProjectListItem } from "./ProjectsLibraryPanel";
import type { YoutubeChannelAlerts } from "./YoutubeStudioPanel";
import type React from "react";

/** Union of values App passes into tab prop bundles (extras + tab prop fields). */
export type AppTabPropContext = Record<string, unknown> & {
  [key: string]: any;
  activeProject: string;
  activeTab: AppTab;
  brandPanelProps: Record<string, unknown>;
  config: ConfigData | null;
  logs: string[];
  openCreatorTab: () => void;
  outputs: OutputVideo[];
  postAi: (
    path: string,
    init?: RequestInit
  ) => Promise<{ ok: boolean; data: Record<string, any> }>;
  projects: ProjectListItem[];
  recentProjects: string[];
  renderProgress?: { percent?: number };
  rendering: boolean;
  onCancelRender?: () => void;
  saveTimelinePatch: (
    cfg: ConfigData,
    opts?: { skipRefresh?: boolean }
  ) => void | Promise<void> | Promise<ConfigData | null>;
  setActiveTab: (tab: AppTab) => void;
  handleSelectProject: (name: string) => void;
  setLogs: React.Dispatch<React.SetStateAction<string[]>>;
  status: WorkspaceStatus | null;
  storyboardData: unknown;
  terminalEndRef: React.RefObject<HTMLDivElement | null>;
  videoQuality: VideoQualityReport | null;
  wordTranscripts: unknown;
  youtubeChannelAlerts: YoutubeChannelAlerts | null;
  safeMusicFiles: MusicFile[];
  localLlmUrlInput: string;
  setLocalLlmUrlInput: (v: string) => void;
  localLlmModelInput: string;
  setLocalLlmModelInput: (v: string) => void;
  omnirouteModel: string;
  setOmnirouteModel: (v: string) => void;
  omnirouteModelOptions: Array<{ id: string; label: string; hint?: string }>;
  setOmnirouteModelOptions: (
    v: Array<{ id: string; label: string; hint?: string }>
  ) => void;
  omnirouteBaseUrlInput: string;
  setOmnirouteBaseUrlInput: (v: string) => void;
  omnirouteKeyInput: string;
  setOmnirouteKeyInput: (v: string) => void;
  ideasProgressLabel?: string;
  hasOmnirouteKey: boolean;
};

export type AppTabPropBundles = {
  creatorTabProps: AppCreatorTabProps;
  aiTabProps: AppAiTabProps;
  uploadTabProps: AppUploadTabProps;
  editorTabProps: AppEditorTabProps;
  settingsTabProps: AppSettingsTabProps;
  statusTabProps: AppStatusTabProps;
  timelineTabProps: AppTimelineTabProps;
  musicTabPanelProps: AppMusicTabPanelProps;
  homeTabProps: AppHomeTabProps;
  workflowTabProps: AppWorkflowTabProps;
  terminalTabProps: AppTerminalTabProps;
};

export function buildAppTabPropBundles(
  ctx: AppTabPropContext
): AppTabPropBundles {
  const creatorTabProps: AppCreatorTabProps = {
    activeProject: ctx.activeProject,
    applyMetadataToUpload: ctx.applyMetadataToUpload,
    applyWizardSessionPatch: ctx.applyWizardSessionPatch,
    bumpCreatorGenToken: ctx.bumpCreatorGenToken,
    applyNarrationGenerationResult: ctx.applyNarrationGenerationResult,
    postAi: ctx.postAi,
    fetchProjects: ctx.fetchProjects,
    setActiveProject: ctx.setActiveProject,
    config: ctx.config,
    copiedSection: ctx.copiedSection,
    copyToClipboard: ctx.copyToClipboard,
    creatorIdeasBundle: ctx.creatorIdeasBundle,
    creatorLoading: ctx.creatorLoading,
    ideasProgressLabel: ctx.ideasProgressLabel,
    creatorLoadingMode: ctx.creatorLoadingMode,
    creatorProjectName: ctx.creatorProjectName,
    creatorScenesNeedRepair: ctx.creatorScenesNeedRepair,
    creatorStep: ctx.creatorStep,
    customBlocks: ctx.customBlocks,
    customHooks: ctx.customHooks,
    customIdeaBlocks: ctx.customIdeaBlocks,
    customIdeaEmotion: ctx.customIdeaEmotion,
    customIdeaHook: ctx.customIdeaHook,
    customIdeaPromise: ctx.customIdeaPromise,
    customIdeaTitle: ctx.customIdeaTitle,
    customIdeaOpportunity: ctx.customIdeaOpportunity,
    customOutline: ctx.customOutline,
    customTitle: ctx.customTitle,
    historicalWitnessContext: ctx.historicalWitnessContext,
    dragActive: ctx.dragActive,
    editorialIdeaImport: ctx.editorialIdeaImport,
    expandedBlocks: ctx.expandedBlocks,
    fetchData: ctx.fetchData,
    formatSelector: ctx.formatSelector,
    geminiBrowserMode: ctx.geminiBrowserMode,
    generateYoutubeMetadata: ctx.generateYoutubeMetadata,
    generatedScriptData: ctx.generatedScriptData,
    getAssetUrl: ctx.getAssetUrl,
    getMusicUrl: ctx.getMusicUrl,
    getProjectUrl: ctx.getProjectUrl,
    handleApproveNarrationAndGenerateScript:
      ctx.handleApproveNarrationAndGenerateScript,
    handleCaptureGeminiNarration: ctx.handleCaptureGeminiNarration,
    handleDrag: ctx.handleDrag,
    handleDrop: ctx.handleDrop,
    handleEnhanceVisualPrompts: ctx.handleEnhanceVisualPrompts,
    handleBuildMotionPlan: ctx.handleBuildMotionPlan,
    handleOpenMotionPlanEditor: ctx.handleOpenMotionPlanEditor,
    handleEvaluateScriptChecklist: ctx.handleEvaluateScriptChecklist,
    handleFileInput: ctx.handleFileInput,
    handleGenerateFullScript: ctx.handleGenerateFullScript,
    handleGenerateIdeas: ctx.handleGenerateIdeas,
    handleGenerateListicleScript: ctx.handleGenerateListicleScript,
    handleGenerateNarration: ctx.handleGenerateNarration,
    handleGenerateNarrationFromImport: ctx.handleGenerateNarrationFromImport,
    handleGenerateYoutubeThumbnailImages:
      ctx.handleGenerateYoutubeThumbnailImages,
    handleNotebooklmImproveNarrationDraft:
      ctx.handleNotebooklmImproveNarrationDraft,
    handleRemoveSceneAsset: ctx.handleRemoveSceneAsset,
    handleSaveConfig: ctx.handleSaveConfig,
    handleSuggestListicleRankings: ctx.handleSuggestListicleRankings,
    handleSyncTimings: ctx.handleSyncTimings,
    handleUpdateCreatorScene: ctx.handleUpdateCreatorScene,
    handleUploadSceneAsset: ctx.handleUploadSceneAsset,
    handleMotionScenesChange: ctx.handleMotionScenesChange,
    hasApiKey: ctx.hasApiKey,
    ideasData: ctx.ideasData,
    ideationTab: ctx.ideationTab,
    leaveGlobalViewForProject: ctx.leaveGlobalViewForProject,
    listNiche: ctx.listNiche,
    listTopic: ctx.listTopic,
    listicleHudStyle: ctx.listicleHudStyle,
    listicleIdeasData: ctx.listicleIdeasData,
    mixBGM: ctx.mixBGM,
    mixing: ctx.mixing,
    narrationBlockPhrases: ctx.narrationBlockPhrases,
    narrationBlockScript: ctx.narrationBlockScript,
    narrationDraft: ctx.narrationDraft,
    narrationNotebooklmEnriched: ctx.narrationNotebooklmEnriched,
    narrationProjectName: ctx.narrationProjectName,
    narrationStrategy: ctx.narrationStrategy,
    narrationTaggedDraft: ctx.narrationTaggedDraft,
    nicheInput: ctx.nicheInput,
    notebooklmImproving: ctx.notebooklmImproving,
    notebooklmStatus: ctx.notebooklmStatus,
    rankCount: ctx.rankCount,
    rankOrder: ctx.rankOrder,
    renderRichTimelineEditor: ctx.renderRichTimelineEditor,
    rendering: ctx.rendering,
    resetCreatorWizard: ctx.resetCreatorWizard,
    saveConfigPatch: ctx.saveConfigPatch,
    saveWizardSession: ctx.saveWizardSession,
    selectedIdeaIndex: ctx.selectedIdeaIndex,
    selectedListicleIdeaIndex: ctx.selectedListicleIdeaIndex,
    setConfig: ctx.setConfig,
    setCreatorProjectName: ctx.setCreatorProjectName,
    setCreatorStep: ctx.setCreatorStep,
    setCustomBlocks: ctx.setCustomBlocks,
    setCustomHooks: ctx.setCustomHooks,
    setCustomIdeaBlocks: ctx.setCustomIdeaBlocks,
    setCustomIdeaEmotion: ctx.setCustomIdeaEmotion,
    setCustomIdeaHook: ctx.setCustomIdeaHook,
    setCustomIdeaPromise: ctx.setCustomIdeaPromise,
    setCustomIdeaTitle: ctx.setCustomIdeaTitle,
    setCustomIdeaOpportunity: ctx.setCustomIdeaOpportunity,
    setCustomOutline: ctx.setCustomOutline,
    setCustomTitle: ctx.setCustomTitle,
    setEditorialIdeaImport: ctx.setEditorialIdeaImport,
    setExpandedBlocks: ctx.setExpandedBlocks,
    setFormatSelector: ctx.setFormatSelector,
    setHistoricalWitnessContext: ctx.setHistoricalWitnessContext,
    setIdeasData: ctx.setIdeasData,
    setIdeationTab: ctx.setIdeationTab,
    setListNiche: ctx.setListNiche,
    setListTopic: ctx.setListTopic,
    setListicleHudStyle: ctx.setListicleHudStyle,
    setNarrationDraft: ctx.setNarrationDraft,
    setNarrationTaggedDraft: ctx.setNarrationTaggedDraft,
    setNicheInput: ctx.setNicheInput,
    setRankCount: ctx.setRankCount,
    setRankOrder: ctx.setRankOrder,
    setSelectedIdeaIndex: ctx.setSelectedIdeaIndex,
    setSelectedListicleIdeaIndex: ctx.setSelectedListicleIdeaIndex,
    setTaggedNarrations: ctx.setTaggedNarrations,
    setUploadSuccess: ctx.setUploadSuccess,
    setUseNotebooklm: ctx.setUseNotebooklm,
    setNotebooklmDeep: ctx.setNotebooklmDeep,
    setEnablePov: ctx.setEnablePov,
    motionTemplatePackEnabled: ctx.motionTemplatePackEnabled,
    setMotionTemplatePackEnabled: ctx.setMotionTemplatePackEnabled,
    motionTemplateNiche: ctx.motionTemplateNiche,
    setMotionTemplateNiche: ctx.setMotionTemplateNiche,
    motionTemplateIds: ctx.motionTemplateIds,
    setMotionTemplateIds: ctx.setMotionTemplateIds,
    showNarrationReview: ctx.showNarrationReview,
    status: ctx.status,
    storyboardData: ctx.storyboardData,
    syncCreatorStoryboard: ctx.syncCreatorStoryboard,
    syncingTimings: ctx.syncingTimings,
    taggedNarrations: ctx.taggedNarrations,
    timelineAssets: ctx.config?.timeline_assets || ctx.timelineAssets,
    triggerRender: ctx.triggerRender,
    uploadSuccess: ctx.uploadSuccess,
    uploadedScenes: ctx.uploadedScenes,
    uploadingNarration: ctx.uploadingNarration,
    useNotebooklm: ctx.useNotebooklm,
    enablePov: ctx.enablePov,
    notebooklmDeep: ctx.notebooklmDeep,
    wizardSavedAtLabel: ctx.wizardSavedAtLabel,
    wordTranscripts: ctx.wordTranscripts,
    youtubeLoading: ctx.youtubeLoading,
    youtubeMetadata: ctx.youtubeMetadata,
    youtubeMetadataParsed: ctx.youtubeMetadataParsed,
  };

  const aiTabProps: AppAiTabProps = {
    activeProject: ctx.activeProject,
    aiProviderBadge: ctx.aiProviderBadge,
    applyAiConfig: ctx.applyAiConfig,
    applyMetadataToUpload: ctx.applyMetadataToUpload,
    canvaThumbnailsLoading: ctx.canvaThumbnailsLoading,
    chatEndRef: ctx.chatEndRef,
    chatInput: ctx.chatInput,
    setChatInput: ctx.setChatInput,
    chatLoading: ctx.chatLoading,
    chatMessages: ctx.chatMessages,
    copiedSection: ctx.copiedSection,
    copyToClipboard: ctx.copyToClipboard,
    fetchTitleExperiment: ctx.fetchTitleExperiment,
    fetchTitleExperimentAnalytics: ctx.fetchTitleExperimentAnalytics,
    getProjectUrl: ctx.getProjectUrl,
    handleApplyTitleVariant: ctx.handleApplyTitleVariant,
    handleGenerateCanvaThumbnails: ctx.handleGenerateCanvaThumbnails,
    handleGenerateYoutubeMetadata: ctx.handleGenerateYoutubeMetadata,
    handleGenerateYoutubeThumbnailImages:
      ctx.handleGenerateYoutubeThumbnailImages,
    handleRelinkYoutube: ctx.handleRelinkYoutube,
    handleSendChatMessage: ctx.handleSendChatMessage,
    handleStartTitleExperiment: ctx.handleStartTitleExperiment,
    hasApiKey: ctx.hasApiKey,
    openCanvaThumbnailDesigner: ctx.openCanvaThumbnailDesigner,
    selectThumbnailForUpload: ctx.selectThumbnailForUpload,
    setActiveTab: ctx.setActiveTab,
    setTitleAbSelected: ctx.setTitleAbSelected,
    setTitleExperimentLoading: ctx.setTitleExperimentLoading,
    setTitleExperimentVideoId: ctx.setTitleExperimentVideoId,
    setYtTitle: ctx.setYtTitle,
    titleAbSelected: ctx.titleAbSelected,
    titleExperiment: ctx.titleExperiment,
    titleExperimentAnalytics: ctx.titleExperimentAnalytics,
    titleExperimentLoading: ctx.titleExperimentLoading,
    titleExperimentRankings: ctx.titleExperimentRankings,
    titleExperimentVideoId: ctx.titleExperimentVideoId,
    titleExperimentWinner: ctx.titleExperimentWinner,
    titleRetention: ctx.titleRetention,
    uploadStatus: ctx.uploadStatus,
    youtubeLoading: ctx.youtubeLoading,
    youtubeMetadata: ctx.youtubeMetadata,
    youtubeMetadataFormat: ctx.youtubeMetadataFormat,
    youtubeMetadataParsed: ctx.youtubeMetadataParsed,
    youtubeMetadataStrategy: ctx.youtubeMetadataStrategy,
    youtubeThumbnailsGenerated: ctx.youtubeThumbnailsGenerated,
    youtubeThumbnailsLoading: ctx.youtubeThumbnailsLoading,
    ytThumbnailVariant: ctx.ytThumbnailVariant,
  };

  const uploadTabProps: AppUploadTabProps = {
    activeProject: ctx.activeProject,
    applyMetadataToUpload: ctx.applyMetadataToUpload,
    config: ctx.config,
    generateYoutubeMetadata: ctx.generateYoutubeMetadata,
    getProjectUrl: ctx.getProjectUrl,
    handleFixYoutubeMetadata: ctx.handleFixYoutubeMetadata,
    handleGenerateYoutubeThumbnailImages:
      ctx.handleGenerateYoutubeThumbnailImages,
    handlePostUploadComplete: ctx.handlePostUploadComplete,
    igCaption: ctx.igCaption,
    setIgCaption: ctx.setIgCaption,
    kwCaption: ctx.kwCaption,
    setKwCaption: ctx.setKwCaption,
    openCanvaThumbnailDesigner: ctx.openCanvaThumbnailDesigner,
    pipelineRunning: ctx.pipelineRunning,
    setPipelineRunning: ctx.setPipelineRunning,
    prepareUploadForPublish: ctx.prepareUploadForPublish,
    saveUploadMetadataToProject: ctx.saveUploadMetadataToProject,
    selectThumbnailForUpload: ctx.selectThumbnailForUpload,
    selectedPlatforms: ctx.selectedPlatforms,
    setSelectedPlatforms: ctx.setSelectedPlatforms,
    selectedUploadVideo: ctx.selectedUploadVideo,
    setActiveTab: ctx.setActiveTab,
    setSettingsSection: ctx.setSettingsSection,
    setThumbnailExperiment: ctx.setThumbnailExperiment,
    setTtCaption: ctx.setTtCaption,
    ttCaption: ctx.ttCaption,
    setUploadLogs: ctx.setUploadLogs,
    uploadLogs: ctx.uploadLogs,
    setUploadProgress: ctx.setUploadProgress,
    uploadProgress: ctx.uploadProgress,
    setUploading: ctx.setUploading,
    uploading: ctx.uploading,
    setYtCategoryId: ctx.setYtCategoryId,
    ytCategoryId: ctx.ytCategoryId,
    setYtContainsSyntheticMedia: ctx.setYtContainsSyntheticMedia,
    ytContainsSyntheticMedia: ctx.ytContainsSyntheticMedia,
    setYtDefaultLanguage: ctx.setYtDefaultLanguage,
    ytDefaultLanguage: ctx.ytDefaultLanguage,
    setYtPlaylistId: ctx.setYtPlaylistId,
    ytPlaylistId: ctx.ytPlaylistId,
    ytPlaylists: ctx.ytPlaylists,
    ytPlaylistsLoading: ctx.ytPlaylistsLoading,
    fetchYoutubePlaylists: ctx.fetchYoutubePlaylists,
    setYtChapters: ctx.setYtChapters,
    ytChapters: ctx.ytChapters,
    setYtDescription: ctx.setYtDescription,
    ytDescription: ctx.ytDescription,
    setYtPinnedComment: ctx.setYtPinnedComment,
    ytPinnedComment: ctx.ytPinnedComment,
    setYtPrivacy: ctx.setYtPrivacy,
    ytPrivacy: ctx.ytPrivacy,
    setYtPublishAt: ctx.setYtPublishAt,
    ytPublishAt: ctx.ytPublishAt,
    setYtTags: ctx.setYtTags,
    ytTags: ctx.ytTags,
    setYtTitle: ctx.setYtTitle,
    ytTitle: ctx.ytTitle,
    titleExperimentVideoId: ctx.titleExperimentVideoId,
    uploadMetadataReady: ctx.uploadMetadataReady,
    uploadStatus: ctx.uploadStatus,
    youtubeMetadataFormat: ctx.youtubeMetadataFormat,
    youtubeThumbnailsGenerated: ctx.youtubeThumbnailsGenerated,
    youtubeThumbnailsLoading: ctx.youtubeThumbnailsLoading,
    ytThumbnailVariant: ctx.ytThumbnailVariant,
  };

  const editorTabProps: AppEditorTabProps = {
    activeProject: ctx.activeProject,
    addSceneAtEnd: ctx.addSceneAtEnd,
    config: ctx.config,
    copiedSection: ctx.copiedSection,
    copyToClipboard: ctx.copyToClipboard,
    debounceSaveStoryboard: ctx.debounceSaveStoryboard,
    deleteScene: ctx.deleteScene,
    editorSubTab: ctx.editorSubTab,
    fetchData: ctx.fetchData,
    generatingOverlays: ctx.generatingOverlays,
    getAssetDuration: ctx.getAssetDuration,
    getAssetUrl: ctx.getAssetUrl,
    getMusicUrl: ctx.getMusicUrl,
    getProjectUrl: ctx.getProjectUrl,
    getTotalVideoDuration: ctx.getTotalVideoDuration,
    handleGenerateAiOverlays: ctx.handleGenerateAiOverlays,
    handleNotebooklmImprove: ctx.handleNotebooklmImprove,
    handleSaveStoryboard: ctx.handleSaveStoryboard,
    handleUploadSceneAsset: ctx.handleUploadSceneAsset,
    hasApiKey: ctx.hasApiKey,
    insertSceneAfter: ctx.insertSceneAfter,
    loadEditorProject: ctx.loadEditorProject,
    loadingStoryboard: ctx.loadingStoryboard,
    moveScene: ctx.moveScene,
    notebooklmImproving: ctx.notebooklmImproving,
    notebooklmStatus: ctx.notebooklmStatus,
    notebooklmSuggestions: ctx.notebooklmSuggestions,
    projects: ctx.projects,
    renderRichTimelineEditor: ctx.renderRichTimelineEditor,
    saveConfigPatch: ctx.saveConfigPatch,
    saveCreatorStoryboard: ctx.saveCreatorStoryboard,
    selectedProject: ctx.selectedProject,
    setActiveTab: ctx.setActiveTab,
    setConfig: ctx.setConfig,
    setEditorSubTab: ctx.setEditorSubTab,
    setSelectedProject: ctx.setSelectedProject,
    setStoryboardData: ctx.setStoryboardData,
    setVideoFileDurations: ctx.setVideoFileDurations,
    status: ctx.status,
    storyboardData: ctx.storyboardData,
    titleExperimentVideoId: ctx.titleExperimentVideoId,
    updateSceneField: ctx.updateSceneField,
    videoFileDurations: ctx.videoFileDurations,
    wordTranscripts: ctx.wordTranscripts,
  };

  const settingsTabProps: AppSettingsTabProps = {
    activeProject: ctx.activeProject,
    aiProvider: ctx.aiProvider,
    applyProductionPatchToConfig: ctx.applyProductionPatchToConfig,
    applyVisualPatchToConfig: ctx.applyVisualPatchToConfig,
    canvaClientId: ctx.canvaClientId,
    canvaClientSecret: ctx.canvaClientSecret,
    config: ctx.config,
    epidemicKeyInput: ctx.epidemicKeyInput,
    formatSelector: ctx.formatSelector,
    fetchUploadStatus: ctx.fetchUploadStatus,
    geminiBrowserMode: ctx.geminiBrowserMode,
    geminiExtensionDiag: ctx.geminiExtensionDiag,
    geminiExtensionReady: ctx.geminiExtensionReady,
    geminiExtensionTesting: ctx.geminiExtensionTesting,
    geminiKeyCount: ctx.geminiKeyCount,
    geminiKeysInput: ctx.geminiKeysInput,
    geminiModel: ctx.geminiModel,
    geminiModelOptions: ctx.geminiModelOptions,
    openrouterModel: ctx.openrouterModel,
    openrouterModelOptions: ctx.openrouterModelOptions,
    nvidiaModel: ctx.nvidiaModel,
    nvidiaModelOptions: ctx.nvidiaModelOptions,
    alibabaModel: ctx.alibabaModel,
    alibabaModelOptions: ctx.alibabaModelOptions,
    alibabaBaseUrlInput: ctx.alibabaBaseUrlInput,
    alibabaKeyInput: ctx.alibabaKeyInput,
    tokenrouterModel: ctx.tokenrouterModel,
    tokenrouterModelOptions: ctx.tokenrouterModelOptions,
    tokenrouterBaseUrlInput: ctx.tokenrouterBaseUrlInput,
    tokenrouterKeyInput: ctx.tokenrouterKeyInput,
    opencodeModel: ctx.opencodeModel,
    opencodeModelOptions: ctx.opencodeModelOptions,
    opencodeBaseUrlInput: ctx.opencodeBaseUrlInput,
    opencodeKeyInput: ctx.opencodeKeyInput,
    hasOpencodeKey: ctx.hasOpencodeKey,
    airforceModel: ctx.airforceModel,
    airforceModelOptions: ctx.airforceModelOptions,
    airforceBaseUrlInput: ctx.airforceBaseUrlInput,
    airforceKeyInput: ctx.airforceKeyInput,
    hasAirforceKey: ctx.hasAirforceKey,
    moonaiModel: ctx.moonaiModel,
    moonaiModelOptions: ctx.moonaiModelOptions,
    moonaiBaseUrlInput: ctx.moonaiBaseUrlInput,
    moonaiKeyInput: ctx.moonaiKeyInput,
    hasMoonaiKey: ctx.hasMoonaiKey,
    omnirouteModel: ctx.omnirouteModel,
    setOmnirouteModel: ctx.setOmnirouteModel,
    omnirouteModelOptions: ctx.omnirouteModelOptions,
    setOmnirouteModelOptions: ctx.setOmnirouteModelOptions,
    omnirouteBaseUrlInput: ctx.omnirouteBaseUrlInput,
    setOmnirouteBaseUrlInput: ctx.setOmnirouteBaseUrlInput,
    omnirouteKeyInput: ctx.omnirouteKeyInput,
    setOmnirouteKeyInput: ctx.setOmnirouteKeyInput,
    hasOmnirouteKey: ctx.hasOmnirouteKey,
    globalBlockGap: ctx.globalBlockGap,
    globalDebugOverlay: ctx.globalDebugOverlay,
    globalFps: ctx.globalFps,
    globalMusicVolume: ctx.globalMusicVolume,
    globalRenderResolution: ctx.globalRenderResolution,
    globalStudioProduction: ctx.globalStudioProduction,
    globalStudioVisual: ctx.globalStudioVisual,
    globalUseRemotion: ctx.globalUseRemotion,
    saveGlobalStudioDefaults: ctx.saveGlobalStudioDefaults,
    handleClearProjectRenderResolution: ctx.handleClearProjectRenderResolution,
    handleRelinkYoutube: ctx.handleRelinkYoutube,
    handleSaveAiSettings: ctx.handleSaveAiSettings,
    handleSaveApiKeys: ctx.handleSaveApiKeys,
    handleSaveGlobalRenderConfig: ctx.handleSaveGlobalRenderConfig,
    handleSaveProjectRenderResolution: ctx.handleSaveProjectRenderResolution,
    handleTestSupermemory: ctx.handleTestSupermemory,
    hasEpidemicKey: ctx.hasEpidemicKey,
    hasNvidiaKey: ctx.hasNvidiaKey,
    hasAlibabaKey: ctx.hasAlibabaKey,
    hasTokenrouterKey: ctx.hasTokenrouterKey,
    hasOpenRouterKey: ctx.hasOpenRouterKey,
    hasPexelsKey: ctx.hasPexelsKey,
    hasPixabayKey: ctx.hasPixabayKey,
    hasSupermemoryKey: ctx.hasSupermemoryKey,
    hasXaiKey: ctx.hasXaiKey,
    igAccessToken: ctx.igAccessToken,
    igAccountId: ctx.igAccountId,
    igAppId: ctx.igAppId,
    igAppSecret: ctx.igAppSecret,
    nvidiaKeyInput: ctx.nvidiaKeyInput,
    openrouterKeyInput: ctx.openrouterKeyInput,
    pexelsKeyInput: ctx.pexelsKeyInput,
    localLlmUrlInput: ctx.localLlmUrlInput,
    setLocalLlmUrlInput: ctx.setLocalLlmUrlInput,
    localLlmModelInput: ctx.localLlmModelInput,
    setLocalLlmModelInput: ctx.setLocalLlmModelInput,
    pickProductionConfig: ctx.pickProductionConfig,
    pickVisualConfig: ctx.pickVisualConfig,
    pixabayKeyInput: ctx.pixabayKeyInput,
    productionDraftToApiPatch: ctx.productionDraftToApiPatch,
    projectDataLoading: ctx.projectDataLoading,
    projectRenderResolution: ctx.projectRenderResolution,
    refreshGeminiExtensionStatus: ctx.refreshGeminiExtensionStatus,
    resolutionConfigScope: ctx.resolutionConfigScope,
    saveConfigPatch: ctx.saveConfigPatch,
    savingAiSettings: ctx.savingAiSettings,
    savingApiKeys: ctx.savingApiKeys,
    savingGlobalConfig: ctx.savingGlobalConfig,
    savingProductionConfig: ctx.savingProductionConfig,
    savingProjectResolution: ctx.savingProjectResolution,
    savingVisualConfig: ctx.savingVisualConfig,
    setAiProvider: ctx.setAiProvider,
    setCanvaClientId: ctx.setCanvaClientId,
    setCanvaClientSecret: ctx.setCanvaClientSecret,
    setConfig: ctx.setConfig,
    setEpidemicKeyInput: ctx.setEpidemicKeyInput,
    setGeminiBrowserMode: ctx.setGeminiBrowserMode,
    setGeminiExtensionTesting: ctx.setGeminiExtensionTesting,
    setGeminiKeysInput: ctx.setGeminiKeysInput,
    setGeminiModel: ctx.setGeminiModel,
    setOpenrouterModel: ctx.setOpenrouterModel,
    setNvidiaModel: ctx.setNvidiaModel,
    setAlibabaModel: ctx.setAlibabaModel,
    setTokenrouterModel: ctx.setTokenrouterModel,
    setTokenrouterBaseUrlInput: ctx.setTokenrouterBaseUrlInput,
    setTokenrouterKeyInput: ctx.setTokenrouterKeyInput,
    setOpencodeModel: ctx.setOpencodeModel,
    setOpencodeBaseUrlInput: ctx.setOpencodeBaseUrlInput,
    setOpencodeKeyInput: ctx.setOpencodeKeyInput,
    setAirforceModel: ctx.setAirforceModel,
    setAirforceBaseUrlInput: ctx.setAirforceBaseUrlInput,
    setAirforceKeyInput: ctx.setAirforceKeyInput,
    setMoonaiModel: ctx.setMoonaiModel,
    setMoonaiBaseUrlInput: ctx.setMoonaiBaseUrlInput,
    setMoonaiKeyInput: ctx.setMoonaiKeyInput,
    setAlibabaBaseUrlInput: ctx.setAlibabaBaseUrlInput,
    setGlobalBlockGap: ctx.setGlobalBlockGap,
    setGlobalDebugOverlay: ctx.setGlobalDebugOverlay,
    setGlobalFps: ctx.setGlobalFps,
    setGlobalMusicVolume: ctx.setGlobalMusicVolume,
    setGlobalRenderResolution: ctx.setGlobalRenderResolution,
    setGlobalUseRemotion: ctx.setGlobalUseRemotion,
    setIgAccessToken: ctx.setIgAccessToken,
    setIgAccountId: ctx.setIgAccountId,
    setIgAppId: ctx.setIgAppId,
    setIgAppSecret: ctx.setIgAppSecret,
    setNvidiaKeyInput: ctx.setNvidiaKeyInput,
    setAlibabaKeyInput: ctx.setAlibabaKeyInput,
    setOpenRouterKeyInput: ctx.setOpenRouterKeyInput,
    setPexelsKeyInput: ctx.setPexelsKeyInput,
    setPixabayKeyInput: ctx.setPixabayKeyInput,
    setProjectRenderResolution: ctx.setProjectRenderResolution,
    setResolutionConfigScope: ctx.setResolutionConfigScope,
    setSavingProductionConfig: ctx.setSavingProductionConfig,
    setSavingVisualConfig: ctx.setSavingVisualConfig,
    setSettingsSection: ctx.setSettingsSection,
    setSupermemoryBaseUrlInput: ctx.setSupermemoryBaseUrlInput,
    setSupermemoryEnabled: ctx.setSupermemoryEnabled,
    setSupermemoryKeyInput: ctx.setSupermemoryKeyInput,
    setXaiKeyInput: ctx.setXaiKeyInput,
    setYtClientId: ctx.setYtClientId,
    setYtClientSecret: ctx.setYtClientSecret,
    settingsSection: ctx.settingsSection,
    supermemoryBaseUrlInput: ctx.supermemoryBaseUrlInput,
    supermemoryEnabled: ctx.supermemoryEnabled,
    supermemoryKeyInput: ctx.supermemoryKeyInput,
    testingSupermemory: ctx.testingSupermemory,
    uploadStatus: ctx.uploadStatus,
    visualDraftToApiPatch: ctx.visualDraftToApiPatch,
    xaiKeyInput: ctx.xaiKeyInput,
    ytClientId: ctx.ytClientId,
    ytClientSecret: ctx.ytClientSecret,
  };

  const statusTabProps: AppStatusTabProps = {
    activeProject: ctx.activeProject,
    brandPanelProps: ctx.brandPanelProps,
    config: ctx.config,
    effectiveRenderResolution: ctx.effectiveRenderResolution,
    fetchVideoQuality: ctx.fetchVideoQuality,
    getFormatBytes: ctx.getFormatBytes,
    handlePreRenderAutoFix: ctx.handlePreRenderAutoFix,
    outputs: ctx.outputs,
    preRenderFixingId: ctx.preRenderFixingId,
    renderResolutionLabel: ctx.renderResolutionLabel,
    rendering: ctx.rendering,
    selectedUploadVideo: ctx.selectedUploadVideo,
    onCancelRender: ctx.onCancelRender,
    setActiveTab: ctx.setActiveTab,
    setPendingOutputDelete: ctx.setPendingOutputDelete,
    setPreviewVideoUrl: ctx.setPreviewVideoUrl,
    setSelectedUploadVideo: ctx.setSelectedUploadVideo,
    status: ctx.status,
    triggerRender: ctx.triggerRender,
    videoQuality: ctx.videoQuality,
    renderFps: ctx.renderFps,
    setRenderFps: ctx.setRenderFps,
  };

  const timelineTabProps: AppTimelineTabProps = {
    activeProject: ctx.activeProject,
    config: ctx.config,
    projectDataLoading: ctx.projectDataLoading,
    fetchData: ctx.fetchData,
    newKeyword: ctx.newKeyword,
    setNewKeyword: ctx.setNewKeyword,
    addKeyword: ctx.addKeyword,
    removeKeyword: ctx.removeKeyword,
    editingImpact: ctx.editingImpact,
    setEditingImpact: ctx.setEditingImpact,
    handleSaveImpactText: ctx.handleSaveImpactText,
  };

  const musicTabPanelProps: AppMusicTabPanelProps = {
    projectDataLoading: ctx.projectDataLoading,
    fetchData: ctx.fetchData,
    config: ctx.config,
    activeProject: ctx.activeProject,
    mixing: ctx.mixing,
    mixBGM: ctx.mixBGM,
    globalMusicVolume: ctx.globalMusicVolume,
    activeBgmMode: ctx.activeBgmMode,
    isShortVideo: ctx.isShortVideo,
    saveConfig: ctx.saveConfig,
    planningBgmEmotions: ctx.planningBgmEmotions,
    hasApiKey: ctx.hasApiKey,
    handlePlanBgmEmotions: ctx.handlePlanBgmEmotions,
    bgmEmotionRows: ctx.bgmEmotionRows,
    safeMusicFiles: ctx.safeMusicFiles,
    handleEmotionMusicChange: ctx.handleEmotionMusicChange,
    playingMusic: ctx.playingMusic,
    togglePlayMusic: ctx.togglePlayMusic,
    bgmSuggestions: ctx.bgmSuggestions,
    bgmBlockRows: ctx.bgmBlockRows,
    handleMusicChange: ctx.handleMusicChange,
    searchMusic: ctx.searchMusic,
    setSearchMusic: ctx.setSearchMusic,
    handleDeleteAllMusic: ctx.handleDeleteAllMusic,
    getProjectUrl: ctx.getProjectUrl,
    suggestingBGM: ctx.suggestingBGM,
    handleSuggestBGM: ctx.handleSuggestBGM,
    handleDeleteMusic: ctx.handleDeleteMusic,
    getFormatBytes: ctx.getFormatBytes,
    hasEpidemicKey: ctx.hasEpidemicKey,
    autoSoundtracking: ctx.autoSoundtracking,
    handleAutoSoundtrack: ctx.handleAutoSoundtrack,
    planningProfessionalSfx: ctx.planningProfessionalSfx,
    handlePlanProfessionalSfx: ctx.handlePlanProfessionalSfx,
    professionalSfxEvents: ctx.professionalSfxEvents,
    epidemicSearchType: ctx.epidemicSearchType,
    setEpidemicSearchType: ctx.setEpidemicSearchType,
    setEpidemicSearchResults: ctx.setEpidemicSearchResults,
    epidemicSearchQuery: ctx.epidemicSearchQuery,
    setEpidemicSearchQuery: ctx.setEpidemicSearchQuery,
    handleSearchEpidemic: ctx.handleSearchEpidemic,
    searchingEpidemic: ctx.searchingEpidemic,
    safeEpidemicResults: ctx.safeEpidemicResults,
    downloadingEpidemicId: ctx.downloadingEpidemicId,
    handleDownloadEpidemic: ctx.handleDownloadEpidemic,
    storyboardData: ctx.storyboardData,
  };
  const homeTabProps: AppHomeTabProps = {
    projects: ctx.projects,
    activeProject: ctx.activeProject,
    recentProjects: ctx.recentProjects,
    status: ctx.status,
    videoQualityScore: ctx.videoQuality?.score,
    outputCount: ctx.outputs.length,
    youtubeAlerts: ctx.youtubeChannelAlerts?.badgeCount ?? 0,
    hotVideos: ctx.youtubeChannelAlerts?.hotVideos,
    rendering: ctx.rendering,
    renderPercent: ctx.renderProgress?.percent,
    openCreatorTab: ctx.openCreatorTab,
    setActiveTab: ctx.setActiveTab,
    onSelectProject: ctx.handleSelectProject,
  };

  const workflowTabProps: AppWorkflowTabProps = {
    activeProject: ctx.activeProject,
    activeTab: ctx.activeTab,
    config: ctx.config,
    status: ctx.status,
    getProjectUrl: ctx.getProjectUrl,
    getMusicUrl: ctx.getMusicUrl,
    postAi: ctx.postAi,
    fetchData: ctx.fetchData,
    setActiveTab: ctx.setActiveTab,
  };

  const terminalTabProps: AppTerminalTabProps = {
    activeProject: ctx.activeProject,
    logs: ctx.logs,
    setLogs: ctx.setLogs,
    terminalEndRef: ctx.terminalEndRef,
  };

  return {
    creatorTabProps,
    aiTabProps,
    uploadTabProps,
    editorTabProps,
    settingsTabProps,
    statusTabProps,
    timelineTabProps,
    musicTabPanelProps,
    homeTabProps,
    workflowTabProps,
    terminalTabProps,
  };
}
