/* eslint-disable */
// AUTO-GENERATED — NUNCA apaga lottie_assets. 477 arquivos, 156 pools.
import { LOTTIE_POOLS } from "./lottiePools.generated";

import * as chunk0 from "./lottie-registry/chunk-0";
import * as chunk1 from "./lottie-registry/chunk-1";
import * as chunk2 from "./lottie-registry/chunk-2";
import * as chunk3 from "./lottie-registry/chunk-3";
import * as chunk4 from "./lottie-registry/chunk-4";
import * as chunk5 from "./lottie-registry/chunk-5";
import * as chunk6 from "./lottie-registry/chunk-6";
import * as chunk7 from "./lottie-registry/chunk-7";
import * as chunk8 from "./lottie-registry/chunk-8";
import * as chunk9 from "./lottie-registry/chunk-9";

function extractChunkEntries(mod: Record<string, unknown>) {
  const out: Record<string, object> = {};
  for (const [k, v] of Object.entries(mod)) {
    if (!k.startsWith("entries_")) continue;
    Object.assign(out, v as Record<string, object>);
  }
  return out;
}

const LOTTIE_BY_FILE: Record<string, object> = {
  ...extractChunkEntries(chunk0),
  ...extractChunkEntries(chunk1),
  ...extractChunkEntries(chunk2),
  ...extractChunkEntries(chunk3),
  ...extractChunkEntries(chunk4),
  ...extractChunkEntries(chunk5),
  ...extractChunkEntries(chunk6),
  ...extractChunkEntries(chunk7),
  ...extractChunkEntries(chunk8),
  ...extractChunkEntries(chunk9),
};

export { LOTTIE_BY_FILE, LOTTIE_POOLS };

export const LOTTIE_REGISTRY: Record<string, object> = {
  "add": LOTTIE_BY_FILE["lottie_ui_add_1.json"],
  "alert": LOTTIE_BY_FILE["lottie_ui_alert_1.json"],
  "analytics": LOTTIE_BY_FILE["lottie_biz_analytics_1.json"],
  "anchor": LOTTIE_BY_FILE["lottie_life_anchor_1.json"],
  "api": LOTTIE_BY_FILE["lottie_tech_api_1.json"],
  "arrow": LOTTIE_BY_FILE["lottie_arrow_arrow_1.json"],
  "award": LOTTIE_BY_FILE["lottie_biz_award_1.json"],
  "bag": LOTTIE_BY_FILE["lottie_biz_bag_1.json"],
  "ball": LOTTIE_BY_FILE["lottie_sports_ball_1.json"],
  "bell": LOTTIE_BY_FILE["lottie_interact_bell_1.json"],
  "bolt": LOTTIE_BY_FILE["lottie_tech_bolt_1.json"],
  "book": LOTTIE_BY_FILE["lottie_edu_book_1.json"],
  "bookmark": LOTTIE_BY_FILE["lottie_interact_bookmark_1.json"],
  "box": LOTTIE_BY_FILE["lottie_biz_box_1.json"],
  "bulb": LOTTIE_BY_FILE["lottie_life_bulb_1.json"],
  "burger": LOTTIE_BY_FILE["lottie_life_burger_1.json"],
  "calendar": LOTTIE_BY_FILE["lottie_ui_calendar_1.json"],
  "camera": LOTTIE_BY_FILE["lottie_tech_camera_1.json"],
  "car": LOTTIE_BY_FILE["lottie_life_car_1.json"],
  "card": LOTTIE_BY_FILE["lottie_biz_card_1.json"],
  "cart": LOTTIE_BY_FILE["lottie_biz_cart_1.json"],
  "cat": LOTTIE_BY_FILE["lottie_nature_cat_1.json"],
  "chart": LOTTIE_BY_FILE["lottie_biz_chart_1.json"],
  "chat": LOTTIE_BY_FILE["lottie_interact_chat_1.json"],
  "check": LOTTIE_BY_FILE["lottie_ui_check_1.json"],
  "checkmark_success": LOTTIE_BY_FILE["checkmark_success.json"],
  "clear_day": LOTTIE_BY_FILE["weather_clear_day.json"],
  "clear_night": LOTTIE_BY_FILE["weather_clear_night.json"],
  "close": LOTTIE_BY_FILE["lottie_ui_close_1.json"],
  "cloud": LOTTIE_BY_FILE["lottie_tech_cloud_1.json"],
  "cloudy": LOTTIE_BY_FILE["weather_cloudy.json"],
  "code": LOTTIE_BY_FILE["lottie_tech_code_1.json"],
  "coffee": LOTTIE_BY_FILE["lottie_life_coffee_1.json"],
  "coin": LOTTIE_BY_FILE["lottie_biz_coin_1.json"],
  "comment": LOTTIE_BY_FILE["lottie_interact_comment_1.json"],
  "copy": LOTTIE_BY_FILE["lottie_tech_copy_1.json"],
  "crown": LOTTIE_BY_FILE["lottie_biz_crown_1.json"],
  "delete": LOTTIE_BY_FILE["lottie_ui_delete_1.json"],
  "delivery": LOTTIE_BY_FILE["lottie_biz_delivery_1.json"],
  "direction": LOTTIE_BY_FILE["lottie_arrow_direction_1.json"],
  "dna": LOTTIE_BY_FILE["lottie_tech_dna_1.json"],
  "document": LOTTIE_BY_FILE["lottie_tech_document_1.json"],
  "dollar": LOTTIE_BY_FILE["lottie_biz_dollar_1.json"],
  "download": LOTTIE_BY_FILE["lottie_ui_download_1.json"],
  "drink": LOTTIE_BY_FILE["lottie_life_drink_1.json"],
  "earth": LOTTIE_BY_FILE["lottie_life_earth_1.json"],
  "edit": LOTTIE_BY_FILE["lottie_ui_edit_1.json"],
  "error": LOTTIE_BY_FILE["lottie_ui_error_1.json"],
  "facebook": LOTTIE_BY_FILE["lottie_social_facebook_1.json"],
  "file": LOTTIE_BY_FILE["lottie_tech_file_1.json"],
  "filter": LOTTIE_BY_FILE["lottie_ui_filter_1.json"],
  "fire": LOTTIE_BY_FILE["lottie_life_fire_1.json"],
  "fitness": LOTTIE_BY_FILE["lottie_life_fitness_1.json"],
  "flame": LOTTIE_BY_FILE["flame.json"],
  "fog": LOTTIE_BY_FILE["weather_fog.json"],
  "folder": LOTTIE_BY_FILE["lottie_tech_folder_1.json"],
  "forward": LOTTIE_BY_FILE["lottie_arrow_forward_1.json"],
  "gear": LOTTIE_BY_FILE["lottie_ui_gear_1.json"],
  "gift": LOTTIE_BY_FILE["lottie_biz_gift_1.json"],
  "github": LOTTIE_BY_FILE["lottie_social_github_1.json"],
  "globe": LOTTIE_BY_FILE["lottie_life_globe_1.json"],
  "graph": LOTTIE_BY_FILE["lottie_biz_graph_1.json"],
  "hail": LOTTIE_BY_FILE["weather_hail.json"],
  "heart": LOTTIE_BY_FILE["lottie_interact_heart_1.json"],
  "help": LOTTIE_BY_FILE["lottie_ui_help_1.json"],
  "home": LOTTIE_BY_FILE["lottie_ui_home_1.json"],
  "hurricane": LOTTIE_BY_FILE["weather_hurricane.json"],
  "idea": LOTTIE_BY_FILE["lottie_life_idea_1.json"],
  "info": LOTTIE_BY_FILE["lottie_ui_info_1.json"],
  "instagram": LOTTIE_BY_FILE["lottie_social_instagram_1.json"],
  "key": LOTTIE_BY_FILE["lottie_ui_key_1.json"],
  "laptop": LOTTIE_BY_FILE["lottie_tech_laptop_1.json"],
  "leaf": LOTTIE_BY_FILE["lottie_nature_leaf_1.json"],
  "lightning": LOTTIE_BY_FILE["lottie_tech_lightning_1.json"],
  "like": LOTTIE_BY_FILE["lottie_interact_like_1.json"],
  "linkedin": LOTTIE_BY_FILE["lottie_social_linkedin_1.json"],
  "location": LOTTIE_BY_FILE["lottie_life_location_1.json"],
  "lock": LOTTIE_BY_FILE["lottie_ui_lock_1.json"],
  "mail": LOTTIE_BY_FILE["lottie_interact_mail_1.json"],
  "map": LOTTIE_BY_FILE["lottie_life_map_1.json"],
  "menu": LOTTIE_BY_FILE["lottie_ui_menu_1.json"],
  "message": LOTTIE_BY_FILE["lottie_interact_message_1.json"],
  "minus": LOTTIE_BY_FILE["lottie_ui_minus_1.json"],
  "mist": LOTTIE_BY_FILE["weather_mist.json"],
  "mobile": LOTTIE_BY_FILE["lottie_tech_mobile_1.json"],
  "money": LOTTIE_BY_FILE["lottie_biz_money_1.json"],
  "mountain": LOTTIE_BY_FILE["lottie_nature_mountain_1.json"],
  "music": LOTTIE_BY_FILE["lottie_tech_music_1.json"],
  "nature": LOTTIE_BY_FILE["lottie_nature_nature_1.json"],
  "pause": LOTTIE_BY_FILE["lottie_arrow_pause_1.json"],
  "phone": LOTTIE_BY_FILE["lottie_interact_phone_1.json"],
  "pillar": LOTTIE_BY_FILE["lottie_edu_pillar_1.json"],
  "pin": LOTTIE_BY_FILE["lottie_life_pin_1.json"],
  "pinterest": LOTTIE_BY_FILE["lottie_social_pinterest_1.json"],
  "pizza": LOTTIE_BY_FILE["lottie_life_pizza_1.json"],
  "plane": LOTTIE_BY_FILE["lottie_life_plane_1.json"],
  "play": LOTTIE_BY_FILE["lottie_arrow_play_1.json"],
  "plus": LOTTIE_BY_FILE["lottie_ui_plus_1.json"],
  "power": LOTTIE_BY_FILE["lottie_tech_power_1.json"],
  "prev": LOTTIE_BY_FILE["lottie_arrow_prev_1.json"],
  "print": LOTTIE_BY_FILE["lottie_tech_print_1.json"],
  "pyramid": LOTTIE_BY_FILE["lottie_nature_pyramid_1.json"],
  "rain": LOTTIE_BY_FILE["weather_rain.json"],
  "refresh": LOTTIE_BY_FILE["lottie_ui_refresh_1.json"],
  "rocket": LOTTIE_BY_FILE["lottie_nature_rocket_1.json"],
  "scroll": LOTTIE_BY_FILE["lottie_edu_scroll_1.json"],
  "search": LOTTIE_BY_FILE["lottie_ui_search_1.json"],
  "send": LOTTIE_BY_FILE["lottie_interact_send_1.json"],
  "server": LOTTIE_BY_FILE["lottie_tech_server_1.json"],
  "settings": LOTTIE_BY_FILE["lottie_ui_settings_1.json"],
  "share": LOTTIE_BY_FILE["lottie_interact_share_1.json"],
  "shield": LOTTIE_BY_FILE["lottie_edu_shield_1.json"],
  "ship": LOTTIE_BY_FILE["lottie_life_ship_2.json"],
  "shop": LOTTIE_BY_FILE["lottie_biz_shop_1.json"],
  "skull": LOTTIE_BY_FILE["lottie_life_skull_1.json"],
  "snow": LOTTIE_BY_FILE["weather_snow.json"],
  "snowflake": LOTTIE_BY_FILE["weather_snowflake.json"],
  "sound": LOTTIE_BY_FILE["lottie_tech_sound_1.json"],
  "sparkles": LOTTIE_BY_FILE["sparkles.json"],
  "sport": LOTTIE_BY_FILE["lottie_sports_sport_1.json"],
  "star": LOTTIE_BY_FILE["lottie_interact_star_1.json"],
  "sun": LOTTIE_BY_FILE["lottie_nature_sun_1.json"],
  "sunrise": LOTTIE_BY_FILE["weather_sunrise.json"],
  "sunset": LOTTIE_BY_FILE["weather_sunset.json"],
  "sync": LOTTIE_BY_FILE["lottie_ui_sync_1.json"],
  "tablet": LOTTIE_BY_FILE["lottie_tech_tablet_1.json"],
  "target": LOTTIE_BY_FILE["lottie_biz_target_1.json"],
  "telegram": LOTTIE_BY_FILE["lottie_social_telegram_1.json"],
  "thermometer": LOTTIE_BY_FILE["weather_thermometer.json"],
  "thunderstorms": LOTTIE_BY_FILE["weather_thunderstorms.json"],
  "thunderstorms_rain": LOTTIE_BY_FILE["weather_thunderstorms_rain.json"],
  "tiktok": LOTTIE_BY_FILE["lottie_social_tiktok_1.json"],
  "time": LOTTIE_BY_FILE["lottie_ui_time_1.json"],
  "tornado": LOTTIE_BY_FILE["weather_tornado.json"],
  "trash": LOTTIE_BY_FILE["lottie_ui_trash_1.json"],
  "tree": LOTTIE_BY_FILE["lottie_nature_tree_1.json"],
  "trophy": LOTTIE_BY_FILE["lottie_biz_trophy_1.json"],
  "truck": LOTTIE_BY_FILE["lottie_biz_truck_1.json"],
  "tv": LOTTIE_BY_FILE["lottie_tech_tv_1.json"],
  "twitter": LOTTIE_BY_FILE["lottie_social_twitter_1.json"],
  "ui_animate_tab_animate_tab_1": LOTTIE_BY_FILE["ui_animate_tab_animate_tab_1.json"],
  "ui_animate_tab_animate_tab_1_example": LOTTIE_BY_FILE["ui_animate_tab_animate_tab_1_example.json"],
  "ui_floating_action_button_ic_fab_animate": LOTTIE_BY_FILE["ui_floating_action_button_ic_fab_animate.json"],
  "ui_ic_fav_ic_fav": LOTTIE_BY_FILE["ui_ic_fav_ic_fav.json"],
  "ui_pagination_indicator_pagination_indicator": LOTTIE_BY_FILE["ui_pagination_indicator_pagination_indicator.json"],
  "upload": LOTTIE_BY_FILE["lottie_ui_upload_1.json"],
  "video": LOTTIE_BY_FILE["lottie_tech_video_1.json"],
  "volume": LOTTIE_BY_FILE["lottie_tech_volume_1.json"],
  "wallet": LOTTIE_BY_FILE["lottie_biz_wallet_1.json"],
  "warning": LOTTIE_BY_FILE["lottie_ui_warning_1.json"],
  "water": LOTTIE_BY_FILE["lottie_nature_water_1.json"],
  "whatsapp": LOTTIE_BY_FILE["lottie_social_whatsapp_1.json"],
  "wifi": LOTTIE_BY_FILE["lottie_tech_wifi_1.json"],
  "wind": LOTTIE_BY_FILE["lottie_nature_wind_1.json"],
  "write": LOTTIE_BY_FILE["lottie_edu_write_1.json"],
  "youtube": LOTTIE_BY_FILE["lottie_social_youtube_1.json"],
};

export const LOTTIE_FILE_COUNT = 477;
export const LOTTIE_KEYS = ["add","alert","analytics","anchor","api","arrow","award","bag","ball","bell","bolt","book","bookmark","box","bulb","burger","calendar","camera","car","card","cart","cat","chart","chat","check","checkmark_success","clear_day","clear_night","close","cloud","cloudy","code","coffee","coin","comment","copy","crown","delete","delivery","direction","dna","document","dollar","download","drink","earth","edit","error","facebook","file","filter","fire","fitness","flame","fog","folder","forward","gear","gift","github","globe","graph","hail","heart","help","home","hurricane","idea","info","instagram","key","laptop","leaf","lightning","like","linkedin","location","lock","mail","map","menu","message","minus","mist","mobile","money","mountain","music","nature","pause","phone","pillar","pin","pinterest","pizza","plane","play","plus","power","prev","print","pyramid","rain","refresh","rocket","scroll","search","send","server","settings","share","shield","ship","shop","skull","snow","snowflake","sound","sparkles","sport","star","sun","sunrise","sunset","sync","tablet","target","telegram","thermometer","thunderstorms","thunderstorms_rain","tiktok","time","tornado","trash","tree","trophy","truck","tv","twitter","ui_animate_tab_animate_tab_1","ui_animate_tab_animate_tab_1_example","ui_floating_action_button_ic_fab_animate","ui_ic_fav_ic_fav","ui_pagination_indicator_pagination_indicator","upload","video","volume","wallet","warning","water","whatsapp","wifi","wind","write","youtube"] as const;
export type LottieRegistryKey = typeof LOTTIE_KEYS[number];
