/* eslint-disable */
// AUTO-GENERATED by scripts/generate-lottie-registry.mjs — do not edit manually
// 155 ícones · 467 arquivos em lottie_assets/

import lottie_add from "./lottie_assets/lottie_ui_add_1.json";
import lottie_alert from "./lottie_assets/lottie_ui_alert_1.json";
import lottie_analytics from "./lottie_assets/lottie_biz_analytics_1.json";
import lottie_anchor from "./lottie_assets/lottie_life_anchor_1.json";
import lottie_api from "./lottie_assets/lottie_tech_api_1.json";
import lottie_arrow from "./lottie_assets/lottie_arrow_arrow_1.json";
import lottie_award from "./lottie_assets/lottie_biz_award_1.json";
import lottie_bag from "./lottie_assets/lottie_biz_bag_1.json";
import lottie_ball from "./lottie_assets/lottie_sports_ball_1.json";
import lottie_bell from "./lottie_assets/lottie_interact_bell_1.json";
import lottie_bolt from "./lottie_assets/lottie_tech_bolt_1.json";
import lottie_book from "./lottie_assets/lottie_edu_book_1.json";
import lottie_bookmark from "./lottie_assets/lottie_interact_bookmark_1.json";
import lottie_box from "./lottie_assets/lottie_biz_box_1.json";
import lottie_bulb from "./lottie_assets/lottie_life_bulb_1.json";
import lottie_burger from "./lottie_assets/lottie_life_burger_1.json";
import lottie_calendar from "./lottie_assets/lottie_ui_calendar_1.json";
import lottie_camera from "./lottie_assets/lottie_tech_camera_1.json";
import lottie_car from "./lottie_assets/lottie_life_car_1.json";
import lottie_card from "./lottie_assets/lottie_biz_card_1.json";
import lottie_cart from "./lottie_assets/lottie_biz_cart_1.json";
import lottie_cat from "./lottie_assets/lottie_nature_cat_1.json";
import lottie_chart from "./lottie_assets/lottie_biz_chart_1.json";
import lottie_chat from "./lottie_assets/lottie_interact_chat_1.json";
import lottie_check from "./lottie_assets/lottie_ui_check_1.json";
import lottie_checkmark_success from "./lottie_assets/checkmark_success.json";
import lottie_clear_day from "./lottie_assets/weather_clear_day.json";
import lottie_clear_night from "./lottie_assets/weather_clear_night.json";
import lottie_close from "./lottie_assets/lottie_ui_close_1.json";
import lottie_cloud from "./lottie_assets/lottie_tech_cloud_1.json";
import lottie_cloudy from "./lottie_assets/weather_cloudy.json";
import lottie_code from "./lottie_assets/lottie_tech_code_1.json";
import lottie_coffee from "./lottie_assets/lottie_life_coffee_1.json";
import lottie_coin from "./lottie_assets/lottie_biz_coin_1.json";
import lottie_comment from "./lottie_assets/lottie_interact_comment_1.json";
import lottie_copy from "./lottie_assets/lottie_tech_copy_1.json";
import lottie_crown from "./lottie_assets/lottie_biz_crown_1.json";
import lottie_delete from "./lottie_assets/lottie_ui_delete_1.json";
import lottie_delivery from "./lottie_assets/lottie_biz_delivery_1.json";
import lottie_direction from "./lottie_assets/lottie_arrow_direction_1.json";
import lottie_dna from "./lottie_assets/lottie_tech_dna_1.json";
import lottie_document from "./lottie_assets/lottie_tech_document_1.json";
import lottie_dollar from "./lottie_assets/lottie_biz_dollar_1.json";
import lottie_download from "./lottie_assets/lottie_ui_download_1.json";
import lottie_drink from "./lottie_assets/lottie_life_drink_1.json";
import lottie_earth from "./lottie_assets/lottie_life_earth_1.json";
import lottie_edit from "./lottie_assets/lottie_ui_edit_1.json";
import lottie_error from "./lottie_assets/lottie_ui_error_1.json";
import lottie_facebook from "./lottie_assets/lottie_social_facebook_1.json";
import lottie_file from "./lottie_assets/lottie_tech_file_1.json";
import lottie_filter from "./lottie_assets/lottie_ui_filter_1.json";
import lottie_fire from "./lottie_assets/lottie_life_fire_1.json";
import lottie_fitness from "./lottie_assets/lottie_life_fitness_1.json";
import lottie_flame from "./lottie_assets/flame.json";
import lottie_fog from "./lottie_assets/weather_fog.json";
import lottie_folder from "./lottie_assets/lottie_tech_folder_1.json";
import lottie_forward from "./lottie_assets/lottie_arrow_forward_1.json";
import lottie_gear from "./lottie_assets/lottie_ui_gear_1.json";
import lottie_gift from "./lottie_assets/lottie_biz_gift_1.json";
import lottie_github from "./lottie_assets/lottie_social_github_1.json";
import lottie_globe from "./lottie_assets/lottie_life_globe_1.json";
import lottie_graph from "./lottie_assets/lottie_biz_graph_1.json";
import lottie_hail from "./lottie_assets/weather_hail.json";
import lottie_heart from "./lottie_assets/lottie_interact_heart_1.json";
import lottie_help from "./lottie_assets/lottie_ui_help_1.json";
import lottie_home from "./lottie_assets/lottie_ui_home_1.json";
import lottie_hurricane from "./lottie_assets/weather_hurricane.json";
import lottie_idea from "./lottie_assets/lottie_life_idea_1.json";
import lottie_info from "./lottie_assets/lottie_ui_info_1.json";
import lottie_instagram from "./lottie_assets/lottie_social_instagram_1.json";
import lottie_key from "./lottie_assets/lottie_ui_key_1.json";
import lottie_laptop from "./lottie_assets/lottie_tech_laptop_1.json";
import lottie_leaf from "./lottie_assets/lottie_nature_leaf_1.json";
import lottie_lightning from "./lottie_assets/lottie_tech_lightning_1.json";
import lottie_like from "./lottie_assets/lottie_interact_like_1.json";
import lottie_linkedin from "./lottie_assets/lottie_social_linkedin_1.json";
import lottie_location from "./lottie_assets/lottie_life_location_1.json";
import lottie_lock from "./lottie_assets/lottie_ui_lock_1.json";
import lottie_mail from "./lottie_assets/lottie_interact_mail_1.json";
import lottie_map from "./lottie_assets/lottie_life_map_1.json";
import lottie_menu from "./lottie_assets/lottie_ui_menu_1.json";
import lottie_message from "./lottie_assets/lottie_interact_message_1.json";
import lottie_minus from "./lottie_assets/lottie_ui_minus_1.json";
import lottie_mist from "./lottie_assets/weather_mist.json";
import lottie_mobile from "./lottie_assets/lottie_tech_mobile_1.json";
import lottie_money from "./lottie_assets/lottie_biz_money_1.json";
import lottie_mountain from "./lottie_assets/lottie_nature_mountain_1.json";
import lottie_music from "./lottie_assets/lottie_tech_music_1.json";
import lottie_nature from "./lottie_assets/lottie_nature_nature_1.json";
import lottie_pause from "./lottie_assets/lottie_arrow_pause_1.json";
import lottie_phone from "./lottie_assets/lottie_interact_phone_1.json";
import lottie_pillar from "./lottie_assets/lottie_edu_pillar_1.json";
import lottie_pin from "./lottie_assets/lottie_life_pin_1.json";
import lottie_pinterest from "./lottie_assets/lottie_social_pinterest_1.json";
import lottie_pizza from "./lottie_assets/lottie_life_pizza_1.json";
import lottie_plane from "./lottie_assets/lottie_life_plane_1.json";
import lottie_play from "./lottie_assets/lottie_arrow_play_1.json";
import lottie_plus from "./lottie_assets/lottie_ui_plus_1.json";
import lottie_power from "./lottie_assets/lottie_tech_power_1.json";
import lottie_prev from "./lottie_assets/lottie_arrow_prev_1.json";
import lottie_print from "./lottie_assets/lottie_tech_print_1.json";
import lottie_pyramid from "./lottie_assets/lottie_nature_pyramid_1.json";
import lottie_rain from "./lottie_assets/weather_rain.json";
import lottie_refresh from "./lottie_assets/lottie_ui_refresh_1.json";
import lottie_rocket from "./lottie_assets/lottie_nature_rocket_1.json";
import lottie_scroll from "./lottie_assets/lottie_edu_scroll_1.json";
import lottie_search from "./lottie_assets/lottie_ui_search_1.json";
import lottie_send from "./lottie_assets/lottie_interact_send_1.json";
import lottie_server from "./lottie_assets/lottie_tech_server_1.json";
import lottie_settings from "./lottie_assets/lottie_ui_settings_1.json";
import lottie_share from "./lottie_assets/lottie_interact_share_1.json";
import lottie_shield from "./lottie_assets/lottie_edu_shield_1.json";
import lottie_shop from "./lottie_assets/lottie_biz_shop_1.json";
import lottie_skull from "./lottie_assets/lottie_life_skull_1.json";
import lottie_snow from "./lottie_assets/weather_snow.json";
import lottie_snowflake from "./lottie_assets/weather_snowflake.json";
import lottie_sound from "./lottie_assets/lottie_tech_sound_1.json";
import lottie_sparkles from "./lottie_assets/sparkles.json";
import lottie_sport from "./lottie_assets/lottie_sports_sport_1.json";
import lottie_star from "./lottie_assets/lottie_interact_star_1.json";
import lottie_sun from "./lottie_assets/lottie_nature_sun_1.json";
import lottie_sunrise from "./lottie_assets/weather_sunrise.json";
import lottie_sunset from "./lottie_assets/weather_sunset.json";
import lottie_sync from "./lottie_assets/lottie_ui_sync_1.json";
import lottie_tablet from "./lottie_assets/lottie_tech_tablet_1.json";
import lottie_target from "./lottie_assets/lottie_biz_target_1.json";
import lottie_telegram from "./lottie_assets/lottie_social_telegram_1.json";
import lottie_thermometer from "./lottie_assets/weather_thermometer.json";
import lottie_thunderstorms from "./lottie_assets/weather_thunderstorms.json";
import lottie_thunderstorms_rain from "./lottie_assets/weather_thunderstorms_rain.json";
import lottie_tiktok from "./lottie_assets/lottie_social_tiktok_1.json";
import lottie_time from "./lottie_assets/lottie_ui_time_1.json";
import lottie_tornado from "./lottie_assets/weather_tornado.json";
import lottie_trash from "./lottie_assets/lottie_ui_trash_1.json";
import lottie_tree from "./lottie_assets/lottie_nature_tree_1.json";
import lottie_trophy from "./lottie_assets/lottie_biz_trophy_1.json";
import lottie_truck from "./lottie_assets/lottie_biz_truck_1.json";
import lottie_tv from "./lottie_assets/lottie_tech_tv_1.json";
import lottie_twitter from "./lottie_assets/lottie_social_twitter_1.json";
import lottie_ui_animate_tab_animate_tab_1 from "./lottie_assets/ui_animate_tab_animate_tab_1.json";
import lottie_ui_animate_tab_animate_tab_1_example from "./lottie_assets/ui_animate_tab_animate_tab_1_example.json";
import lottie_ui_floating_action_button_ic_fab_animate from "./lottie_assets/ui_floating_action_button_ic_fab_animate.json";
import lottie_ui_ic_fav_ic_fav from "./lottie_assets/ui_ic_fav_ic_fav.json";
import lottie_ui_pagination_indicator_pagination_indicator from "./lottie_assets/ui_pagination_indicator_pagination_indicator.json";
import lottie_upload from "./lottie_assets/lottie_ui_upload_1.json";
import lottie_video from "./lottie_assets/lottie_tech_video_1.json";
import lottie_volume from "./lottie_assets/lottie_tech_volume_1.json";
import lottie_wallet from "./lottie_assets/lottie_biz_wallet_1.json";
import lottie_warning from "./lottie_assets/lottie_ui_warning_1.json";
import lottie_water from "./lottie_assets/lottie_nature_water_1.json";
import lottie_whatsapp from "./lottie_assets/lottie_social_whatsapp_1.json";
import lottie_wifi from "./lottie_assets/lottie_tech_wifi_1.json";
import lottie_wind from "./lottie_assets/lottie_nature_wind_1.json";
import lottie_write from "./lottie_assets/lottie_edu_write_1.json";
import lottie_youtube from "./lottie_assets/lottie_social_youtube_1.json";

export const LOTTIE_REGISTRY: Record<string, object> = {
  "add": lottie_add,
  "alert": lottie_alert,
  "analytics": lottie_analytics,
  "anchor": lottie_anchor,
  "api": lottie_api,
  "arrow": lottie_arrow,
  "award": lottie_award,
  "bag": lottie_bag,
  "ball": lottie_ball,
  "bell": lottie_bell,
  "bolt": lottie_bolt,
  "book": lottie_book,
  "bookmark": lottie_bookmark,
  "box": lottie_box,
  "bulb": lottie_bulb,
  "burger": lottie_burger,
  "calendar": lottie_calendar,
  "camera": lottie_camera,
  "car": lottie_car,
  "card": lottie_card,
  "cart": lottie_cart,
  "cat": lottie_cat,
  "chart": lottie_chart,
  "chat": lottie_chat,
  "check": lottie_check,
  "checkmark_success": lottie_checkmark_success,
  "clear_day": lottie_clear_day,
  "clear_night": lottie_clear_night,
  "close": lottie_close,
  "cloud": lottie_cloud,
  "cloudy": lottie_cloudy,
  "code": lottie_code,
  "coffee": lottie_coffee,
  "coin": lottie_coin,
  "comment": lottie_comment,
  "copy": lottie_copy,
  "crown": lottie_crown,
  "delete": lottie_delete,
  "delivery": lottie_delivery,
  "direction": lottie_direction,
  "dna": lottie_dna,
  "document": lottie_document,
  "dollar": lottie_dollar,
  "download": lottie_download,
  "drink": lottie_drink,
  "earth": lottie_earth,
  "edit": lottie_edit,
  "error": lottie_error,
  "facebook": lottie_facebook,
  "file": lottie_file,
  "filter": lottie_filter,
  "fire": lottie_fire,
  "fitness": lottie_fitness,
  "flame": lottie_flame,
  "fog": lottie_fog,
  "folder": lottie_folder,
  "forward": lottie_forward,
  "gear": lottie_gear,
  "gift": lottie_gift,
  "github": lottie_github,
  "globe": lottie_globe,
  "graph": lottie_graph,
  "hail": lottie_hail,
  "heart": lottie_heart,
  "help": lottie_help,
  "home": lottie_home,
  "hurricane": lottie_hurricane,
  "idea": lottie_idea,
  "info": lottie_info,
  "instagram": lottie_instagram,
  "key": lottie_key,
  "laptop": lottie_laptop,
  "leaf": lottie_leaf,
  "lightning": lottie_lightning,
  "like": lottie_like,
  "linkedin": lottie_linkedin,
  "location": lottie_location,
  "lock": lottie_lock,
  "mail": lottie_mail,
  "map": lottie_map,
  "menu": lottie_menu,
  "message": lottie_message,
  "minus": lottie_minus,
  "mist": lottie_mist,
  "mobile": lottie_mobile,
  "money": lottie_money,
  "mountain": lottie_mountain,
  "music": lottie_music,
  "nature": lottie_nature,
  "pause": lottie_pause,
  "phone": lottie_phone,
  "pillar": lottie_pillar,
  "pin": lottie_pin,
  "pinterest": lottie_pinterest,
  "pizza": lottie_pizza,
  "plane": lottie_plane,
  "play": lottie_play,
  "plus": lottie_plus,
  "power": lottie_power,
  "prev": lottie_prev,
  "print": lottie_print,
  "pyramid": lottie_pyramid,
  "rain": lottie_rain,
  "refresh": lottie_refresh,
  "rocket": lottie_rocket,
  "scroll": lottie_scroll,
  "search": lottie_search,
  "send": lottie_send,
  "server": lottie_server,
  "settings": lottie_settings,
  "share": lottie_share,
  "shield": lottie_shield,
  "shop": lottie_shop,
  "skull": lottie_skull,
  "snow": lottie_snow,
  "snowflake": lottie_snowflake,
  "sound": lottie_sound,
  "sparkles": lottie_sparkles,
  "sport": lottie_sport,
  "star": lottie_star,
  "sun": lottie_sun,
  "sunrise": lottie_sunrise,
  "sunset": lottie_sunset,
  "sync": lottie_sync,
  "tablet": lottie_tablet,
  "target": lottie_target,
  "telegram": lottie_telegram,
  "thermometer": lottie_thermometer,
  "thunderstorms": lottie_thunderstorms,
  "thunderstorms_rain": lottie_thunderstorms_rain,
  "tiktok": lottie_tiktok,
  "time": lottie_time,
  "tornado": lottie_tornado,
  "trash": lottie_trash,
  "tree": lottie_tree,
  "trophy": lottie_trophy,
  "truck": lottie_truck,
  "tv": lottie_tv,
  "twitter": lottie_twitter,
  "ui_animate_tab_animate_tab_1": lottie_ui_animate_tab_animate_tab_1,
  "ui_animate_tab_animate_tab_1_example": lottie_ui_animate_tab_animate_tab_1_example,
  "ui_floating_action_button_ic_fab_animate": lottie_ui_floating_action_button_ic_fab_animate,
  "ui_ic_fav_ic_fav": lottie_ui_ic_fav_ic_fav,
  "ui_pagination_indicator_pagination_indicator": lottie_ui_pagination_indicator_pagination_indicator,
  "upload": lottie_upload,
  "video": lottie_video,
  "volume": lottie_volume,
  "wallet": lottie_wallet,
  "warning": lottie_warning,
  "water": lottie_water,
  "whatsapp": lottie_whatsapp,
  "wifi": lottie_wifi,
  "wind": lottie_wind,
  "write": lottie_write,
  "youtube": lottie_youtube,
};

export const LOTTIE_KEYS = ["add","alert","analytics","anchor","api","arrow","award","bag","ball","bell","bolt","book","bookmark","box","bulb","burger","calendar","camera","car","card","cart","cat","chart","chat","check","checkmark_success","clear_day","clear_night","close","cloud","cloudy","code","coffee","coin","comment","copy","crown","delete","delivery","direction","dna","document","dollar","download","drink","earth","edit","error","facebook","file","filter","fire","fitness","flame","fog","folder","forward","gear","gift","github","globe","graph","hail","heart","help","home","hurricane","idea","info","instagram","key","laptop","leaf","lightning","like","linkedin","location","lock","mail","map","menu","message","minus","mist","mobile","money","mountain","music","nature","pause","phone","pillar","pin","pinterest","pizza","plane","play","plus","power","prev","print","pyramid","rain","refresh","rocket","scroll","search","send","server","settings","share","shield","shop","skull","snow","snowflake","sound","sparkles","sport","star","sun","sunrise","sunset","sync","tablet","target","telegram","thermometer","thunderstorms","thunderstorms_rain","tiktok","time","tornado","trash","tree","trophy","truck","tv","twitter","ui_animate_tab_animate_tab_1","ui_animate_tab_animate_tab_1_example","ui_floating_action_button_ic_fab_animate","ui_ic_fav_ic_fav","ui_pagination_indicator_pagination_indicator","upload","video","volume","wallet","warning","water","whatsapp","wifi","wind","write","youtube"] as const;
export type LottieRegistryKey = typeof LOTTIE_KEYS[number];
