/* eslint-disable */
import lf_lottie_social_telegram_2 from "../lottie_assets/lottie_social_telegram_2.json";
export const entries_5_lf_lottie_social_telegram_2 = { "lottie_social_telegram_2.json": lf_lottie_social_telegram_2 };
import lf_lottie_social_telegram_3 from "../lottie_assets/lottie_social_telegram_3.json";
export const entries_5_lf_lottie_social_telegram_3 = { "lottie_social_telegram_3.json": lf_lottie_social_telegram_3 };
import lf_lottie_social_telegram_4 from "../lottie_assets/lottie_social_telegram_4.json";
export const entries_5_lf_lottie_social_telegram_4 = { "lottie_social_telegram_4.json": lf_lottie_social_telegram_4 };
import lf_lottie_social_telegram_5 from "../lottie_assets/lottie_social_telegram_5.json";
export const entries_5_lf_lottie_social_telegram_5 = { "lottie_social_telegram_5.json": lf_lottie_social_telegram_5 };
import lf_lottie_social_tiktok_1 from "../lottie_assets/lottie_social_tiktok_1.json";
export const entries_5_lf_lottie_social_tiktok_1 = { "lottie_social_tiktok_1.json": lf_lottie_social_tiktok_1 };
import lf_lottie_social_tiktok_2 from "../lottie_assets/lottie_social_tiktok_2.json";
export const entries_5_lf_lottie_social_tiktok_2 = { "lottie_social_tiktok_2.json": lf_lottie_social_tiktok_2 };
import lf_lottie_social_tiktok_3 from "../lottie_assets/lottie_social_tiktok_3.json";
export const entries_5_lf_lottie_social_tiktok_3 = { "lottie_social_tiktok_3.json": lf_lottie_social_tiktok_3 };
import lf_lottie_social_tiktok_4 from "../lottie_assets/lottie_social_tiktok_4.json";
export const entries_5_lf_lottie_social_tiktok_4 = { "lottie_social_tiktok_4.json": lf_lottie_social_tiktok_4 };
import lf_lottie_social_tiktok_5 from "../lottie_assets/lottie_social_tiktok_5.json";
export const entries_5_lf_lottie_social_tiktok_5 = { "lottie_social_tiktok_5.json": lf_lottie_social_tiktok_5 };
import lf_lottie_social_twitter_1 from "../lottie_assets/lottie_social_twitter_1.json";
export const entries_5_lf_lottie_social_twitter_1 = { "lottie_social_twitter_1.json": lf_lottie_social_twitter_1 };
import lf_lottie_social_twitter_2 from "../lottie_assets/lottie_social_twitter_2.json";
export const entries_5_lf_lottie_social_twitter_2 = { "lottie_social_twitter_2.json": lf_lottie_social_twitter_2 };
import lf_lottie_social_twitter_3 from "../lottie_assets/lottie_social_twitter_3.json";
export const entries_5_lf_lottie_social_twitter_3 = { "lottie_social_twitter_3.json": lf_lottie_social_twitter_3 };
import lf_lottie_social_twitter_4 from "../lottie_assets/lottie_social_twitter_4.json";
export const entries_5_lf_lottie_social_twitter_4 = { "lottie_social_twitter_4.json": lf_lottie_social_twitter_4 };
import lf_lottie_social_twitter_5 from "../lottie_assets/lottie_social_twitter_5.json";
export const entries_5_lf_lottie_social_twitter_5 = { "lottie_social_twitter_5.json": lf_lottie_social_twitter_5 };
import lf_lottie_social_whatsapp_1 from "../lottie_assets/lottie_social_whatsapp_1.json";
export const entries_5_lf_lottie_social_whatsapp_1 = { "lottie_social_whatsapp_1.json": lf_lottie_social_whatsapp_1 };
import lf_lottie_social_whatsapp_2 from "../lottie_assets/lottie_social_whatsapp_2.json";
export const entries_5_lf_lottie_social_whatsapp_2 = { "lottie_social_whatsapp_2.json": lf_lottie_social_whatsapp_2 };
import lf_lottie_social_whatsapp_3 from "../lottie_assets/lottie_social_whatsapp_3.json";
export const entries_5_lf_lottie_social_whatsapp_3 = { "lottie_social_whatsapp_3.json": lf_lottie_social_whatsapp_3 };
import lf_lottie_social_youtube_1 from "../lottie_assets/lottie_social_youtube_1.json";
export const entries_5_lf_lottie_social_youtube_1 = { "lottie_social_youtube_1.json": lf_lottie_social_youtube_1 };
import lf_lottie_social_youtube_2 from "../lottie_assets/lottie_social_youtube_2.json";
export const entries_5_lf_lottie_social_youtube_2 = { "lottie_social_youtube_2.json": lf_lottie_social_youtube_2 };
import lf_lottie_social_youtube_3 from "../lottie_assets/lottie_social_youtube_3.json";
export const entries_5_lf_lottie_social_youtube_3 = { "lottie_social_youtube_3.json": lf_lottie_social_youtube_3 };
import lf_lottie_social_youtube_4 from "../lottie_assets/lottie_social_youtube_4.json";
export const entries_5_lf_lottie_social_youtube_4 = { "lottie_social_youtube_4.json": lf_lottie_social_youtube_4 };
import lf_lottie_social_youtube_5 from "../lottie_assets/lottie_social_youtube_5.json";
export const entries_5_lf_lottie_social_youtube_5 = { "lottie_social_youtube_5.json": lf_lottie_social_youtube_5 };
import lf_lottie_sports_ball_1 from "../lottie_assets/lottie_sports_ball_1.json";
export const entries_5_lf_lottie_sports_ball_1 = { "lottie_sports_ball_1.json": lf_lottie_sports_ball_1 };
import lf_lottie_sports_sport_1 from "../lottie_assets/lottie_sports_sport_1.json";
export const entries_5_lf_lottie_sports_sport_1 = { "lottie_sports_sport_1.json": lf_lottie_sports_sport_1 };
import lf_lottie_sports_sport_2 from "../lottie_assets/lottie_sports_sport_2.json";
export const entries_5_lf_lottie_sports_sport_2 = { "lottie_sports_sport_2.json": lf_lottie_sports_sport_2 };
import lf_lottie_tech_api_1 from "../lottie_assets/lottie_tech_api_1.json";
export const entries_5_lf_lottie_tech_api_1 = { "lottie_tech_api_1.json": lf_lottie_tech_api_1 };
import lf_lottie_tech_api_2 from "../lottie_assets/lottie_tech_api_2.json";
export const entries_5_lf_lottie_tech_api_2 = { "lottie_tech_api_2.json": lf_lottie_tech_api_2 };
import lf_lottie_tech_api_3 from "../lottie_assets/lottie_tech_api_3.json";
export const entries_5_lf_lottie_tech_api_3 = { "lottie_tech_api_3.json": lf_lottie_tech_api_3 };
import lf_lottie_tech_api_4 from "../lottie_assets/lottie_tech_api_4.json";
export const entries_5_lf_lottie_tech_api_4 = { "lottie_tech_api_4.json": lf_lottie_tech_api_4 };
import lf_lottie_tech_bolt_1 from "../lottie_assets/lottie_tech_bolt_1.json";
export const entries_5_lf_lottie_tech_bolt_1 = { "lottie_tech_bolt_1.json": lf_lottie_tech_bolt_1 };
import lf_lottie_tech_bolt_2 from "../lottie_assets/lottie_tech_bolt_2.json";
export const entries_5_lf_lottie_tech_bolt_2 = { "lottie_tech_bolt_2.json": lf_lottie_tech_bolt_2 };
import lf_lottie_tech_bolt_3 from "../lottie_assets/lottie_tech_bolt_3.json";
export const entries_5_lf_lottie_tech_bolt_3 = { "lottie_tech_bolt_3.json": lf_lottie_tech_bolt_3 };
import lf_lottie_tech_bolt_4 from "../lottie_assets/lottie_tech_bolt_4.json";
export const entries_5_lf_lottie_tech_bolt_4 = { "lottie_tech_bolt_4.json": lf_lottie_tech_bolt_4 };
import lf_lottie_tech_bolt_5 from "../lottie_assets/lottie_tech_bolt_5.json";
export const entries_5_lf_lottie_tech_bolt_5 = { "lottie_tech_bolt_5.json": lf_lottie_tech_bolt_5 };
import lf_lottie_tech_camera_1 from "../lottie_assets/lottie_tech_camera_1.json";
export const entries_5_lf_lottie_tech_camera_1 = { "lottie_tech_camera_1.json": lf_lottie_tech_camera_1 };
import lf_lottie_tech_camera_2 from "../lottie_assets/lottie_tech_camera_2.json";
export const entries_5_lf_lottie_tech_camera_2 = { "lottie_tech_camera_2.json": lf_lottie_tech_camera_2 };
import lf_lottie_tech_camera_3 from "../lottie_assets/lottie_tech_camera_3.json";
export const entries_5_lf_lottie_tech_camera_3 = { "lottie_tech_camera_3.json": lf_lottie_tech_camera_3 };
import lf_lottie_tech_cloud_1 from "../lottie_assets/lottie_tech_cloud_1.json";
export const entries_5_lf_lottie_tech_cloud_1 = { "lottie_tech_cloud_1.json": lf_lottie_tech_cloud_1 };
import lf_lottie_tech_cloud_2 from "../lottie_assets/lottie_tech_cloud_2.json";
export const entries_5_lf_lottie_tech_cloud_2 = { "lottie_tech_cloud_2.json": lf_lottie_tech_cloud_2 };
import lf_lottie_tech_cloud_3 from "../lottie_assets/lottie_tech_cloud_3.json";
export const entries_5_lf_lottie_tech_cloud_3 = { "lottie_tech_cloud_3.json": lf_lottie_tech_cloud_3 };
import lf_lottie_tech_cloud_4 from "../lottie_assets/lottie_tech_cloud_4.json";
export const entries_5_lf_lottie_tech_cloud_4 = { "lottie_tech_cloud_4.json": lf_lottie_tech_cloud_4 };
import lf_lottie_tech_code_1 from "../lottie_assets/lottie_tech_code_1.json";
export const entries_5_lf_lottie_tech_code_1 = { "lottie_tech_code_1.json": lf_lottie_tech_code_1 };
import lf_lottie_tech_code_2 from "../lottie_assets/lottie_tech_code_2.json";
export const entries_5_lf_lottie_tech_code_2 = { "lottie_tech_code_2.json": lf_lottie_tech_code_2 };
import lf_lottie_tech_code_3 from "../lottie_assets/lottie_tech_code_3.json";
export const entries_5_lf_lottie_tech_code_3 = { "lottie_tech_code_3.json": lf_lottie_tech_code_3 };
import lf_lottie_tech_code_4 from "../lottie_assets/lottie_tech_code_4.json";
export const entries_5_lf_lottie_tech_code_4 = { "lottie_tech_code_4.json": lf_lottie_tech_code_4 };
import lf_lottie_tech_code_5 from "../lottie_assets/lottie_tech_code_5.json";
export const entries_5_lf_lottie_tech_code_5 = { "lottie_tech_code_5.json": lf_lottie_tech_code_5 };
import lf_lottie_tech_copy_1 from "../lottie_assets/lottie_tech_copy_1.json";
export const entries_5_lf_lottie_tech_copy_1 = { "lottie_tech_copy_1.json": lf_lottie_tech_copy_1 };
import lf_lottie_tech_dna_1 from "../lottie_assets/lottie_tech_dna_1.json";
export const entries_5_lf_lottie_tech_dna_1 = { "lottie_tech_dna_1.json": lf_lottie_tech_dna_1 };
