/* eslint-disable */
import lf_lottie_tech_dna_2 from "../lottie_assets/lottie_tech_dna_2.json";
export const entries_6_lf_lottie_tech_dna_2 = { "lottie_tech_dna_2.json": lf_lottie_tech_dna_2 };
import lf_lottie_tech_document_1 from "../lottie_assets/lottie_tech_document_1.json";
export const entries_6_lf_lottie_tech_document_1 = { "lottie_tech_document_1.json": lf_lottie_tech_document_1 };
import lf_lottie_tech_document_2 from "../lottie_assets/lottie_tech_document_2.json";
export const entries_6_lf_lottie_tech_document_2 = { "lottie_tech_document_2.json": lf_lottie_tech_document_2 };
import lf_lottie_tech_document_3 from "../lottie_assets/lottie_tech_document_3.json";
export const entries_6_lf_lottie_tech_document_3 = { "lottie_tech_document_3.json": lf_lottie_tech_document_3 };
import lf_lottie_tech_file_1 from "../lottie_assets/lottie_tech_file_1.json";
export const entries_6_lf_lottie_tech_file_1 = { "lottie_tech_file_1.json": lf_lottie_tech_file_1 };
import lf_lottie_tech_file_2 from "../lottie_assets/lottie_tech_file_2.json";
export const entries_6_lf_lottie_tech_file_2 = { "lottie_tech_file_2.json": lf_lottie_tech_file_2 };
import lf_lottie_tech_file_3 from "../lottie_assets/lottie_tech_file_3.json";
export const entries_6_lf_lottie_tech_file_3 = { "lottie_tech_file_3.json": lf_lottie_tech_file_3 };
import lf_lottie_tech_file_4 from "../lottie_assets/lottie_tech_file_4.json";
export const entries_6_lf_lottie_tech_file_4 = { "lottie_tech_file_4.json": lf_lottie_tech_file_4 };
import lf_lottie_tech_file_5 from "../lottie_assets/lottie_tech_file_5.json";
export const entries_6_lf_lottie_tech_file_5 = { "lottie_tech_file_5.json": lf_lottie_tech_file_5 };
import lf_lottie_tech_folder_1 from "../lottie_assets/lottie_tech_folder_1.json";
export const entries_6_lf_lottie_tech_folder_1 = { "lottie_tech_folder_1.json": lf_lottie_tech_folder_1 };
import lf_lottie_tech_folder_2 from "../lottie_assets/lottie_tech_folder_2.json";
export const entries_6_lf_lottie_tech_folder_2 = { "lottie_tech_folder_2.json": lf_lottie_tech_folder_2 };
import lf_lottie_tech_folder_3 from "../lottie_assets/lottie_tech_folder_3.json";
export const entries_6_lf_lottie_tech_folder_3 = { "lottie_tech_folder_3.json": lf_lottie_tech_folder_3 };
import lf_lottie_tech_folder_4 from "../lottie_assets/lottie_tech_folder_4.json";
export const entries_6_lf_lottie_tech_folder_4 = { "lottie_tech_folder_4.json": lf_lottie_tech_folder_4 };
import lf_lottie_tech_folder_5 from "../lottie_assets/lottie_tech_folder_5.json";
export const entries_6_lf_lottie_tech_folder_5 = { "lottie_tech_folder_5.json": lf_lottie_tech_folder_5 };
import lf_lottie_tech_laptop_1 from "../lottie_assets/lottie_tech_laptop_1.json";
export const entries_6_lf_lottie_tech_laptop_1 = { "lottie_tech_laptop_1.json": lf_lottie_tech_laptop_1 };
import lf_lottie_tech_laptop_2 from "../lottie_assets/lottie_tech_laptop_2.json";
export const entries_6_lf_lottie_tech_laptop_2 = { "lottie_tech_laptop_2.json": lf_lottie_tech_laptop_2 };
import lf_lottie_tech_lightning_1 from "../lottie_assets/lottie_tech_lightning_1.json";
export const entries_6_lf_lottie_tech_lightning_1 = { "lottie_tech_lightning_1.json": lf_lottie_tech_lightning_1 };
import lf_lottie_tech_lightning_2 from "../lottie_assets/lottie_tech_lightning_2.json";
export const entries_6_lf_lottie_tech_lightning_2 = { "lottie_tech_lightning_2.json": lf_lottie_tech_lightning_2 };
import lf_lottie_tech_mobile_1 from "../lottie_assets/lottie_tech_mobile_1.json";
export const entries_6_lf_lottie_tech_mobile_1 = { "lottie_tech_mobile_1.json": lf_lottie_tech_mobile_1 };
import lf_lottie_tech_mobile_2 from "../lottie_assets/lottie_tech_mobile_2.json";
export const entries_6_lf_lottie_tech_mobile_2 = { "lottie_tech_mobile_2.json": lf_lottie_tech_mobile_2 };
import lf_lottie_tech_mobile_3 from "../lottie_assets/lottie_tech_mobile_3.json";
export const entries_6_lf_lottie_tech_mobile_3 = { "lottie_tech_mobile_3.json": lf_lottie_tech_mobile_3 };
import lf_lottie_tech_music_1 from "../lottie_assets/lottie_tech_music_1.json";
export const entries_6_lf_lottie_tech_music_1 = { "lottie_tech_music_1.json": lf_lottie_tech_music_1 };
import lf_lottie_tech_music_2 from "../lottie_assets/lottie_tech_music_2.json";
export const entries_6_lf_lottie_tech_music_2 = { "lottie_tech_music_2.json": lf_lottie_tech_music_2 };
import lf_lottie_tech_music_3 from "../lottie_assets/lottie_tech_music_3.json";
export const entries_6_lf_lottie_tech_music_3 = { "lottie_tech_music_3.json": lf_lottie_tech_music_3 };
import lf_lottie_tech_music_4 from "../lottie_assets/lottie_tech_music_4.json";
export const entries_6_lf_lottie_tech_music_4 = { "lottie_tech_music_4.json": lf_lottie_tech_music_4 };
import lf_lottie_tech_power_1 from "../lottie_assets/lottie_tech_power_1.json";
export const entries_6_lf_lottie_tech_power_1 = { "lottie_tech_power_1.json": lf_lottie_tech_power_1 };
import lf_lottie_tech_power_2 from "../lottie_assets/lottie_tech_power_2.json";
export const entries_6_lf_lottie_tech_power_2 = { "lottie_tech_power_2.json": lf_lottie_tech_power_2 };
import lf_lottie_tech_print_1 from "../lottie_assets/lottie_tech_print_1.json";
export const entries_6_lf_lottie_tech_print_1 = { "lottie_tech_print_1.json": lf_lottie_tech_print_1 };
import lf_lottie_tech_print_2 from "../lottie_assets/lottie_tech_print_2.json";
export const entries_6_lf_lottie_tech_print_2 = { "lottie_tech_print_2.json": lf_lottie_tech_print_2 };
import lf_lottie_tech_print_3 from "../lottie_assets/lottie_tech_print_3.json";
export const entries_6_lf_lottie_tech_print_3 = { "lottie_tech_print_3.json": lf_lottie_tech_print_3 };
import lf_lottie_tech_server_1 from "../lottie_assets/lottie_tech_server_1.json";
export const entries_6_lf_lottie_tech_server_1 = { "lottie_tech_server_1.json": lf_lottie_tech_server_1 };
import lf_lottie_tech_server_2 from "../lottie_assets/lottie_tech_server_2.json";
export const entries_6_lf_lottie_tech_server_2 = { "lottie_tech_server_2.json": lf_lottie_tech_server_2 };
import lf_lottie_tech_server_3 from "../lottie_assets/lottie_tech_server_3.json";
export const entries_6_lf_lottie_tech_server_3 = { "lottie_tech_server_3.json": lf_lottie_tech_server_3 };
import lf_lottie_tech_sound_1 from "../lottie_assets/lottie_tech_sound_1.json";
export const entries_6_lf_lottie_tech_sound_1 = { "lottie_tech_sound_1.json": lf_lottie_tech_sound_1 };
import lf_lottie_tech_sound_2 from "../lottie_assets/lottie_tech_sound_2.json";
export const entries_6_lf_lottie_tech_sound_2 = { "lottie_tech_sound_2.json": lf_lottie_tech_sound_2 };
import lf_lottie_tech_sound_3 from "../lottie_assets/lottie_tech_sound_3.json";
export const entries_6_lf_lottie_tech_sound_3 = { "lottie_tech_sound_3.json": lf_lottie_tech_sound_3 };
import lf_lottie_tech_tablet_1 from "../lottie_assets/lottie_tech_tablet_1.json";
export const entries_6_lf_lottie_tech_tablet_1 = { "lottie_tech_tablet_1.json": lf_lottie_tech_tablet_1 };
import lf_lottie_tech_tv_1 from "../lottie_assets/lottie_tech_tv_1.json";
export const entries_6_lf_lottie_tech_tv_1 = { "lottie_tech_tv_1.json": lf_lottie_tech_tv_1 };
import lf_lottie_tech_tv_2 from "../lottie_assets/lottie_tech_tv_2.json";
export const entries_6_lf_lottie_tech_tv_2 = { "lottie_tech_tv_2.json": lf_lottie_tech_tv_2 };
import lf_lottie_tech_video_1 from "../lottie_assets/lottie_tech_video_1.json";
export const entries_6_lf_lottie_tech_video_1 = { "lottie_tech_video_1.json": lf_lottie_tech_video_1 };
import lf_lottie_tech_video_2 from "../lottie_assets/lottie_tech_video_2.json";
export const entries_6_lf_lottie_tech_video_2 = { "lottie_tech_video_2.json": lf_lottie_tech_video_2 };
import lf_lottie_tech_video_3 from "../lottie_assets/lottie_tech_video_3.json";
export const entries_6_lf_lottie_tech_video_3 = { "lottie_tech_video_3.json": lf_lottie_tech_video_3 };
import lf_lottie_tech_video_4 from "../lottie_assets/lottie_tech_video_4.json";
export const entries_6_lf_lottie_tech_video_4 = { "lottie_tech_video_4.json": lf_lottie_tech_video_4 };
import lf_lottie_tech_video_5 from "../lottie_assets/lottie_tech_video_5.json";
export const entries_6_lf_lottie_tech_video_5 = { "lottie_tech_video_5.json": lf_lottie_tech_video_5 };
import lf_lottie_tech_volume_1 from "../lottie_assets/lottie_tech_volume_1.json";
export const entries_6_lf_lottie_tech_volume_1 = { "lottie_tech_volume_1.json": lf_lottie_tech_volume_1 };
import lf_lottie_tech_wifi_1 from "../lottie_assets/lottie_tech_wifi_1.json";
export const entries_6_lf_lottie_tech_wifi_1 = { "lottie_tech_wifi_1.json": lf_lottie_tech_wifi_1 };
import lf_lottie_tech_wifi_2 from "../lottie_assets/lottie_tech_wifi_2.json";
export const entries_6_lf_lottie_tech_wifi_2 = { "lottie_tech_wifi_2.json": lf_lottie_tech_wifi_2 };
import lf_lottie_tech_wifi_3 from "../lottie_assets/lottie_tech_wifi_3.json";
export const entries_6_lf_lottie_tech_wifi_3 = { "lottie_tech_wifi_3.json": lf_lottie_tech_wifi_3 };
