/* eslint-disable */
import lf_lottie_life_pin_5 from "../lottie_assets/lottie_life_pin_5.json";
export const entries_4_lf_lottie_life_pin_5 = { "lottie_life_pin_5.json": lf_lottie_life_pin_5 };
import lf_lottie_life_pizza_1 from "../lottie_assets/lottie_life_pizza_1.json";
export const entries_4_lf_lottie_life_pizza_1 = { "lottie_life_pizza_1.json": lf_lottie_life_pizza_1 };
import lf_lottie_life_pizza_2 from "../lottie_assets/lottie_life_pizza_2.json";
export const entries_4_lf_lottie_life_pizza_2 = { "lottie_life_pizza_2.json": lf_lottie_life_pizza_2 };
import lf_lottie_life_pizza_3 from "../lottie_assets/lottie_life_pizza_3.json";
export const entries_4_lf_lottie_life_pizza_3 = { "lottie_life_pizza_3.json": lf_lottie_life_pizza_3 };
import lf_lottie_life_pizza_4 from "../lottie_assets/lottie_life_pizza_4.json";
export const entries_4_lf_lottie_life_pizza_4 = { "lottie_life_pizza_4.json": lf_lottie_life_pizza_4 };
import lf_lottie_life_pizza_5 from "../lottie_assets/lottie_life_pizza_5.json";
export const entries_4_lf_lottie_life_pizza_5 = { "lottie_life_pizza_5.json": lf_lottie_life_pizza_5 };
import lf_lottie_life_plane_1 from "../lottie_assets/lottie_life_plane_1.json";
export const entries_4_lf_lottie_life_plane_1 = { "lottie_life_plane_1.json": lf_lottie_life_plane_1 };
import lf_lottie_life_plane_2 from "../lottie_assets/lottie_life_plane_2.json";
export const entries_4_lf_lottie_life_plane_2 = { "lottie_life_plane_2.json": lf_lottie_life_plane_2 };
import lf_lottie_life_ship_2 from "../lottie_assets/lottie_life_ship_2.json";
export const entries_4_lf_lottie_life_ship_2 = { "lottie_life_ship_2.json": lf_lottie_life_ship_2 };
import lf_lottie_life_skull_1 from "../lottie_assets/lottie_life_skull_1.json";
export const entries_4_lf_lottie_life_skull_1 = { "lottie_life_skull_1.json": lf_lottie_life_skull_1 };
import lf_lottie_life_skull_2 from "../lottie_assets/lottie_life_skull_2.json";
export const entries_4_lf_lottie_life_skull_2 = { "lottie_life_skull_2.json": lf_lottie_life_skull_2 };
import lf_lottie_nature_cat_1 from "../lottie_assets/lottie_nature_cat_1.json";
export const entries_4_lf_lottie_nature_cat_1 = { "lottie_nature_cat_1.json": lf_lottie_nature_cat_1 };
import lf_lottie_nature_cat_2 from "../lottie_assets/lottie_nature_cat_2.json";
export const entries_4_lf_lottie_nature_cat_2 = { "lottie_nature_cat_2.json": lf_lottie_nature_cat_2 };
import lf_lottie_nature_leaf_1 from "../lottie_assets/lottie_nature_leaf_1.json";
export const entries_4_lf_lottie_nature_leaf_1 = { "lottie_nature_leaf_1.json": lf_lottie_nature_leaf_1 };
import lf_lottie_nature_mountain_1 from "../lottie_assets/lottie_nature_mountain_1.json";
export const entries_4_lf_lottie_nature_mountain_1 = { "lottie_nature_mountain_1.json": lf_lottie_nature_mountain_1 };
import lf_lottie_nature_mountain_2 from "../lottie_assets/lottie_nature_mountain_2.json";
export const entries_4_lf_lottie_nature_mountain_2 = { "lottie_nature_mountain_2.json": lf_lottie_nature_mountain_2 };
import lf_lottie_nature_nature_1 from "../lottie_assets/lottie_nature_nature_1.json";
export const entries_4_lf_lottie_nature_nature_1 = { "lottie_nature_nature_1.json": lf_lottie_nature_nature_1 };
import lf_lottie_nature_pyramid_1 from "../lottie_assets/lottie_nature_pyramid_1.json";
export const entries_4_lf_lottie_nature_pyramid_1 = { "lottie_nature_pyramid_1.json": lf_lottie_nature_pyramid_1 };
import lf_lottie_nature_pyramid_2 from "../lottie_assets/lottie_nature_pyramid_2.json";
export const entries_4_lf_lottie_nature_pyramid_2 = { "lottie_nature_pyramid_2.json": lf_lottie_nature_pyramid_2 };
import lf_lottie_nature_rocket_1 from "../lottie_assets/lottie_nature_rocket_1.json";
export const entries_4_lf_lottie_nature_rocket_1 = { "lottie_nature_rocket_1.json": lf_lottie_nature_rocket_1 };
import lf_lottie_nature_rocket_2 from "../lottie_assets/lottie_nature_rocket_2.json";
export const entries_4_lf_lottie_nature_rocket_2 = { "lottie_nature_rocket_2.json": lf_lottie_nature_rocket_2 };
import lf_lottie_nature_rocket_3 from "../lottie_assets/lottie_nature_rocket_3.json";
export const entries_4_lf_lottie_nature_rocket_3 = { "lottie_nature_rocket_3.json": lf_lottie_nature_rocket_3 };
import lf_lottie_nature_rocket_4 from "../lottie_assets/lottie_nature_rocket_4.json";
export const entries_4_lf_lottie_nature_rocket_4 = { "lottie_nature_rocket_4.json": lf_lottie_nature_rocket_4 };
import lf_lottie_nature_sun_1 from "../lottie_assets/lottie_nature_sun_1.json";
export const entries_4_lf_lottie_nature_sun_1 = { "lottie_nature_sun_1.json": lf_lottie_nature_sun_1 };
import lf_lottie_nature_tree_1 from "../lottie_assets/lottie_nature_tree_1.json";
export const entries_4_lf_lottie_nature_tree_1 = { "lottie_nature_tree_1.json": lf_lottie_nature_tree_1 };
import lf_lottie_nature_water_1 from "../lottie_assets/lottie_nature_water_1.json";
export const entries_4_lf_lottie_nature_water_1 = { "lottie_nature_water_1.json": lf_lottie_nature_water_1 };
import lf_lottie_nature_water_2 from "../lottie_assets/lottie_nature_water_2.json";
export const entries_4_lf_lottie_nature_water_2 = { "lottie_nature_water_2.json": lf_lottie_nature_water_2 };
import lf_lottie_nature_wind_1 from "../lottie_assets/lottie_nature_wind_1.json";
export const entries_4_lf_lottie_nature_wind_1 = { "lottie_nature_wind_1.json": lf_lottie_nature_wind_1 };
import lf_lottie_social_facebook_1 from "../lottie_assets/lottie_social_facebook_1.json";
export const entries_4_lf_lottie_social_facebook_1 = { "lottie_social_facebook_1.json": lf_lottie_social_facebook_1 };
import lf_lottie_social_facebook_2 from "../lottie_assets/lottie_social_facebook_2.json";
export const entries_4_lf_lottie_social_facebook_2 = { "lottie_social_facebook_2.json": lf_lottie_social_facebook_2 };
import lf_lottie_social_facebook_3 from "../lottie_assets/lottie_social_facebook_3.json";
export const entries_4_lf_lottie_social_facebook_3 = { "lottie_social_facebook_3.json": lf_lottie_social_facebook_3 };
import lf_lottie_social_facebook_4 from "../lottie_assets/lottie_social_facebook_4.json";
export const entries_4_lf_lottie_social_facebook_4 = { "lottie_social_facebook_4.json": lf_lottie_social_facebook_4 };
import lf_lottie_social_facebook_5 from "../lottie_assets/lottie_social_facebook_5.json";
export const entries_4_lf_lottie_social_facebook_5 = { "lottie_social_facebook_5.json": lf_lottie_social_facebook_5 };
import lf_lottie_social_github_1 from "../lottie_assets/lottie_social_github_1.json";
export const entries_4_lf_lottie_social_github_1 = { "lottie_social_github_1.json": lf_lottie_social_github_1 };
import lf_lottie_social_instagram_1 from "../lottie_assets/lottie_social_instagram_1.json";
export const entries_4_lf_lottie_social_instagram_1 = { "lottie_social_instagram_1.json": lf_lottie_social_instagram_1 };
import lf_lottie_social_instagram_2 from "../lottie_assets/lottie_social_instagram_2.json";
export const entries_4_lf_lottie_social_instagram_2 = { "lottie_social_instagram_2.json": lf_lottie_social_instagram_2 };
import lf_lottie_social_instagram_3 from "../lottie_assets/lottie_social_instagram_3.json";
export const entries_4_lf_lottie_social_instagram_3 = { "lottie_social_instagram_3.json": lf_lottie_social_instagram_3 };
import lf_lottie_social_instagram_4 from "../lottie_assets/lottie_social_instagram_4.json";
export const entries_4_lf_lottie_social_instagram_4 = { "lottie_social_instagram_4.json": lf_lottie_social_instagram_4 };
import lf_lottie_social_instagram_5 from "../lottie_assets/lottie_social_instagram_5.json";
export const entries_4_lf_lottie_social_instagram_5 = { "lottie_social_instagram_5.json": lf_lottie_social_instagram_5 };
import lf_lottie_social_linkedin_1 from "../lottie_assets/lottie_social_linkedin_1.json";
export const entries_4_lf_lottie_social_linkedin_1 = { "lottie_social_linkedin_1.json": lf_lottie_social_linkedin_1 };
import lf_lottie_social_linkedin_2 from "../lottie_assets/lottie_social_linkedin_2.json";
export const entries_4_lf_lottie_social_linkedin_2 = { "lottie_social_linkedin_2.json": lf_lottie_social_linkedin_2 };
import lf_lottie_social_linkedin_3 from "../lottie_assets/lottie_social_linkedin_3.json";
export const entries_4_lf_lottie_social_linkedin_3 = { "lottie_social_linkedin_3.json": lf_lottie_social_linkedin_3 };
import lf_lottie_social_linkedin_4 from "../lottie_assets/lottie_social_linkedin_4.json";
export const entries_4_lf_lottie_social_linkedin_4 = { "lottie_social_linkedin_4.json": lf_lottie_social_linkedin_4 };
import lf_lottie_social_pinterest_1 from "../lottie_assets/lottie_social_pinterest_1.json";
export const entries_4_lf_lottie_social_pinterest_1 = { "lottie_social_pinterest_1.json": lf_lottie_social_pinterest_1 };
import lf_lottie_social_pinterest_2 from "../lottie_assets/lottie_social_pinterest_2.json";
export const entries_4_lf_lottie_social_pinterest_2 = { "lottie_social_pinterest_2.json": lf_lottie_social_pinterest_2 };
import lf_lottie_social_pinterest_3 from "../lottie_assets/lottie_social_pinterest_3.json";
export const entries_4_lf_lottie_social_pinterest_3 = { "lottie_social_pinterest_3.json": lf_lottie_social_pinterest_3 };
import lf_lottie_social_pinterest_4 from "../lottie_assets/lottie_social_pinterest_4.json";
export const entries_4_lf_lottie_social_pinterest_4 = { "lottie_social_pinterest_4.json": lf_lottie_social_pinterest_4 };
import lf_lottie_social_telegram_1 from "../lottie_assets/lottie_social_telegram_1.json";
export const entries_4_lf_lottie_social_telegram_1 = { "lottie_social_telegram_1.json": lf_lottie_social_telegram_1 };
