/* eslint-disable */
import lf_lottie_ui_gear_1 from "../lottie_assets/lottie_ui_gear_1.json";
export const entries_8_lf_lottie_ui_gear_1 = { "lottie_ui_gear_1.json": lf_lottie_ui_gear_1 };
import lf_lottie_ui_gear_2 from "../lottie_assets/lottie_ui_gear_2.json";
export const entries_8_lf_lottie_ui_gear_2 = { "lottie_ui_gear_2.json": lf_lottie_ui_gear_2 };
import lf_lottie_ui_gear_3 from "../lottie_assets/lottie_ui_gear_3.json";
export const entries_8_lf_lottie_ui_gear_3 = { "lottie_ui_gear_3.json": lf_lottie_ui_gear_3 };
import lf_lottie_ui_help_1 from "../lottie_assets/lottie_ui_help_1.json";
export const entries_8_lf_lottie_ui_help_1 = { "lottie_ui_help_1.json": lf_lottie_ui_help_1 };
import lf_lottie_ui_help_2 from "../lottie_assets/lottie_ui_help_2.json";
export const entries_8_lf_lottie_ui_help_2 = { "lottie_ui_help_2.json": lf_lottie_ui_help_2 };
import lf_lottie_ui_help_3 from "../lottie_assets/lottie_ui_help_3.json";
export const entries_8_lf_lottie_ui_help_3 = { "lottie_ui_help_3.json": lf_lottie_ui_help_3 };
import lf_lottie_ui_help_4 from "../lottie_assets/lottie_ui_help_4.json";
export const entries_8_lf_lottie_ui_help_4 = { "lottie_ui_help_4.json": lf_lottie_ui_help_4 };
import lf_lottie_ui_help_5 from "../lottie_assets/lottie_ui_help_5.json";
export const entries_8_lf_lottie_ui_help_5 = { "lottie_ui_help_5.json": lf_lottie_ui_help_5 };
import lf_lottie_ui_home_1 from "../lottie_assets/lottie_ui_home_1.json";
export const entries_8_lf_lottie_ui_home_1 = { "lottie_ui_home_1.json": lf_lottie_ui_home_1 };
import lf_lottie_ui_home_2 from "../lottie_assets/lottie_ui_home_2.json";
export const entries_8_lf_lottie_ui_home_2 = { "lottie_ui_home_2.json": lf_lottie_ui_home_2 };
import lf_lottie_ui_home_3 from "../lottie_assets/lottie_ui_home_3.json";
export const entries_8_lf_lottie_ui_home_3 = { "lottie_ui_home_3.json": lf_lottie_ui_home_3 };
import lf_lottie_ui_home_4 from "../lottie_assets/lottie_ui_home_4.json";
export const entries_8_lf_lottie_ui_home_4 = { "lottie_ui_home_4.json": lf_lottie_ui_home_4 };
import lf_lottie_ui_home_5 from "../lottie_assets/lottie_ui_home_5.json";
export const entries_8_lf_lottie_ui_home_5 = { "lottie_ui_home_5.json": lf_lottie_ui_home_5 };
import lf_lottie_ui_info_1 from "../lottie_assets/lottie_ui_info_1.json";
export const entries_8_lf_lottie_ui_info_1 = { "lottie_ui_info_1.json": lf_lottie_ui_info_1 };
import lf_lottie_ui_info_2 from "../lottie_assets/lottie_ui_info_2.json";
export const entries_8_lf_lottie_ui_info_2 = { "lottie_ui_info_2.json": lf_lottie_ui_info_2 };
import lf_lottie_ui_info_3 from "../lottie_assets/lottie_ui_info_3.json";
export const entries_8_lf_lottie_ui_info_3 = { "lottie_ui_info_3.json": lf_lottie_ui_info_3 };
import lf_lottie_ui_info_4 from "../lottie_assets/lottie_ui_info_4.json";
export const entries_8_lf_lottie_ui_info_4 = { "lottie_ui_info_4.json": lf_lottie_ui_info_4 };
import lf_lottie_ui_info_5 from "../lottie_assets/lottie_ui_info_5.json";
export const entries_8_lf_lottie_ui_info_5 = { "lottie_ui_info_5.json": lf_lottie_ui_info_5 };
import lf_lottie_ui_key_1 from "../lottie_assets/lottie_ui_key_1.json";
export const entries_8_lf_lottie_ui_key_1 = { "lottie_ui_key_1.json": lf_lottie_ui_key_1 };
import lf_lottie_ui_key_2 from "../lottie_assets/lottie_ui_key_2.json";
export const entries_8_lf_lottie_ui_key_2 = { "lottie_ui_key_2.json": lf_lottie_ui_key_2 };
import lf_lottie_ui_key_3 from "../lottie_assets/lottie_ui_key_3.json";
export const entries_8_lf_lottie_ui_key_3 = { "lottie_ui_key_3.json": lf_lottie_ui_key_3 };
import lf_lottie_ui_lock_1 from "../lottie_assets/lottie_ui_lock_1.json";
export const entries_8_lf_lottie_ui_lock_1 = { "lottie_ui_lock_1.json": lf_lottie_ui_lock_1 };
import lf_lottie_ui_lock_2 from "../lottie_assets/lottie_ui_lock_2.json";
export const entries_8_lf_lottie_ui_lock_2 = { "lottie_ui_lock_2.json": lf_lottie_ui_lock_2 };
import lf_lottie_ui_lock_3 from "../lottie_assets/lottie_ui_lock_3.json";
export const entries_8_lf_lottie_ui_lock_3 = { "lottie_ui_lock_3.json": lf_lottie_ui_lock_3 };
import lf_lottie_ui_lock_4 from "../lottie_assets/lottie_ui_lock_4.json";
export const entries_8_lf_lottie_ui_lock_4 = { "lottie_ui_lock_4.json": lf_lottie_ui_lock_4 };
import lf_lottie_ui_lock_5 from "../lottie_assets/lottie_ui_lock_5.json";
export const entries_8_lf_lottie_ui_lock_5 = { "lottie_ui_lock_5.json": lf_lottie_ui_lock_5 };
import lf_lottie_ui_menu_1 from "../lottie_assets/lottie_ui_menu_1.json";
export const entries_8_lf_lottie_ui_menu_1 = { "lottie_ui_menu_1.json": lf_lottie_ui_menu_1 };
import lf_lottie_ui_menu_2 from "../lottie_assets/lottie_ui_menu_2.json";
export const entries_8_lf_lottie_ui_menu_2 = { "lottie_ui_menu_2.json": lf_lottie_ui_menu_2 };
import lf_lottie_ui_menu_3 from "../lottie_assets/lottie_ui_menu_3.json";
export const entries_8_lf_lottie_ui_menu_3 = { "lottie_ui_menu_3.json": lf_lottie_ui_menu_3 };
import lf_lottie_ui_menu_4 from "../lottie_assets/lottie_ui_menu_4.json";
export const entries_8_lf_lottie_ui_menu_4 = { "lottie_ui_menu_4.json": lf_lottie_ui_menu_4 };
import lf_lottie_ui_menu_5 from "../lottie_assets/lottie_ui_menu_5.json";
export const entries_8_lf_lottie_ui_menu_5 = { "lottie_ui_menu_5.json": lf_lottie_ui_menu_5 };
import lf_lottie_ui_minus_1 from "../lottie_assets/lottie_ui_minus_1.json";
export const entries_8_lf_lottie_ui_minus_1 = { "lottie_ui_minus_1.json": lf_lottie_ui_minus_1 };
import lf_lottie_ui_plus_1 from "../lottie_assets/lottie_ui_plus_1.json";
export const entries_8_lf_lottie_ui_plus_1 = { "lottie_ui_plus_1.json": lf_lottie_ui_plus_1 };
import lf_lottie_ui_plus_2 from "../lottie_assets/lottie_ui_plus_2.json";
export const entries_8_lf_lottie_ui_plus_2 = { "lottie_ui_plus_2.json": lf_lottie_ui_plus_2 };
import lf_lottie_ui_plus_3 from "../lottie_assets/lottie_ui_plus_3.json";
export const entries_8_lf_lottie_ui_plus_3 = { "lottie_ui_plus_3.json": lf_lottie_ui_plus_3 };
import lf_lottie_ui_refresh_1 from "../lottie_assets/lottie_ui_refresh_1.json";
export const entries_8_lf_lottie_ui_refresh_1 = { "lottie_ui_refresh_1.json": lf_lottie_ui_refresh_1 };
import lf_lottie_ui_refresh_2 from "../lottie_assets/lottie_ui_refresh_2.json";
export const entries_8_lf_lottie_ui_refresh_2 = { "lottie_ui_refresh_2.json": lf_lottie_ui_refresh_2 };
import lf_lottie_ui_refresh_3 from "../lottie_assets/lottie_ui_refresh_3.json";
export const entries_8_lf_lottie_ui_refresh_3 = { "lottie_ui_refresh_3.json": lf_lottie_ui_refresh_3 };
import lf_lottie_ui_refresh_4 from "../lottie_assets/lottie_ui_refresh_4.json";
export const entries_8_lf_lottie_ui_refresh_4 = { "lottie_ui_refresh_4.json": lf_lottie_ui_refresh_4 };
import lf_lottie_ui_search_1 from "../lottie_assets/lottie_ui_search_1.json";
export const entries_8_lf_lottie_ui_search_1 = { "lottie_ui_search_1.json": lf_lottie_ui_search_1 };
import lf_lottie_ui_search_2 from "../lottie_assets/lottie_ui_search_2.json";
export const entries_8_lf_lottie_ui_search_2 = { "lottie_ui_search_2.json": lf_lottie_ui_search_2 };
import lf_lottie_ui_search_3 from "../lottie_assets/lottie_ui_search_3.json";
export const entries_8_lf_lottie_ui_search_3 = { "lottie_ui_search_3.json": lf_lottie_ui_search_3 };
import lf_lottie_ui_search_4 from "../lottie_assets/lottie_ui_search_4.json";
export const entries_8_lf_lottie_ui_search_4 = { "lottie_ui_search_4.json": lf_lottie_ui_search_4 };
import lf_lottie_ui_search_5 from "../lottie_assets/lottie_ui_search_5.json";
export const entries_8_lf_lottie_ui_search_5 = { "lottie_ui_search_5.json": lf_lottie_ui_search_5 };
import lf_lottie_ui_settings_1 from "../lottie_assets/lottie_ui_settings_1.json";
export const entries_8_lf_lottie_ui_settings_1 = { "lottie_ui_settings_1.json": lf_lottie_ui_settings_1 };
import lf_lottie_ui_settings_2 from "../lottie_assets/lottie_ui_settings_2.json";
export const entries_8_lf_lottie_ui_settings_2 = { "lottie_ui_settings_2.json": lf_lottie_ui_settings_2 };
import lf_lottie_ui_settings_3 from "../lottie_assets/lottie_ui_settings_3.json";
export const entries_8_lf_lottie_ui_settings_3 = { "lottie_ui_settings_3.json": lf_lottie_ui_settings_3 };
import lf_lottie_ui_settings_4 from "../lottie_assets/lottie_ui_settings_4.json";
export const entries_8_lf_lottie_ui_settings_4 = { "lottie_ui_settings_4.json": lf_lottie_ui_settings_4 };
