/* eslint-disable */
import lf_lottie_interact_share_5 from "../lottie_assets/lottie_interact_share_5.json";
export const entries_3_lf_lottie_interact_share_5 = { "lottie_interact_share_5.json": lf_lottie_interact_share_5 };
import lf_lottie_interact_star_1 from "../lottie_assets/lottie_interact_star_1.json";
export const entries_3_lf_lottie_interact_star_1 = { "lottie_interact_star_1.json": lf_lottie_interact_star_1 };
import lf_lottie_interact_star_2 from "../lottie_assets/lottie_interact_star_2.json";
export const entries_3_lf_lottie_interact_star_2 = { "lottie_interact_star_2.json": lf_lottie_interact_star_2 };
import lf_lottie_interact_star_3 from "../lottie_assets/lottie_interact_star_3.json";
export const entries_3_lf_lottie_interact_star_3 = { "lottie_interact_star_3.json": lf_lottie_interact_star_3 };
import lf_lottie_interact_star_4 from "../lottie_assets/lottie_interact_star_4.json";
export const entries_3_lf_lottie_interact_star_4 = { "lottie_interact_star_4.json": lf_lottie_interact_star_4 };
import lf_lottie_interact_star_5 from "../lottie_assets/lottie_interact_star_5.json";
export const entries_3_lf_lottie_interact_star_5 = { "lottie_interact_star_5.json": lf_lottie_interact_star_5 };
import lf_lottie_life_anchor_1 from "../lottie_assets/lottie_life_anchor_1.json";
export const entries_3_lf_lottie_life_anchor_1 = { "lottie_life_anchor_1.json": lf_lottie_life_anchor_1 };
import lf_lottie_life_anchor_2 from "../lottie_assets/lottie_life_anchor_2.json";
export const entries_3_lf_lottie_life_anchor_2 = { "lottie_life_anchor_2.json": lf_lottie_life_anchor_2 };
import lf_lottie_life_bulb_1 from "../lottie_assets/lottie_life_bulb_1.json";
export const entries_3_lf_lottie_life_bulb_1 = { "lottie_life_bulb_1.json": lf_lottie_life_bulb_1 };
import lf_lottie_life_bulb_2 from "../lottie_assets/lottie_life_bulb_2.json";
export const entries_3_lf_lottie_life_bulb_2 = { "lottie_life_bulb_2.json": lf_lottie_life_bulb_2 };
import lf_lottie_life_burger_1 from "../lottie_assets/lottie_life_burger_1.json";
export const entries_3_lf_lottie_life_burger_1 = { "lottie_life_burger_1.json": lf_lottie_life_burger_1 };
import lf_lottie_life_burger_2 from "../lottie_assets/lottie_life_burger_2.json";
export const entries_3_lf_lottie_life_burger_2 = { "lottie_life_burger_2.json": lf_lottie_life_burger_2 };
import lf_lottie_life_burger_3 from "../lottie_assets/lottie_life_burger_3.json";
export const entries_3_lf_lottie_life_burger_3 = { "lottie_life_burger_3.json": lf_lottie_life_burger_3 };
import lf_lottie_life_burger_4 from "../lottie_assets/lottie_life_burger_4.json";
export const entries_3_lf_lottie_life_burger_4 = { "lottie_life_burger_4.json": lf_lottie_life_burger_4 };
import lf_lottie_life_burger_5 from "../lottie_assets/lottie_life_burger_5.json";
export const entries_3_lf_lottie_life_burger_5 = { "lottie_life_burger_5.json": lf_lottie_life_burger_5 };
import lf_lottie_life_car_1 from "../lottie_assets/lottie_life_car_1.json";
export const entries_3_lf_lottie_life_car_1 = { "lottie_life_car_1.json": lf_lottie_life_car_1 };
import lf_lottie_life_car_2 from "../lottie_assets/lottie_life_car_2.json";
export const entries_3_lf_lottie_life_car_2 = { "lottie_life_car_2.json": lf_lottie_life_car_2 };
import lf_lottie_life_car_3 from "../lottie_assets/lottie_life_car_3.json";
export const entries_3_lf_lottie_life_car_3 = { "lottie_life_car_3.json": lf_lottie_life_car_3 };
import lf_lottie_life_coffee_1 from "../lottie_assets/lottie_life_coffee_1.json";
export const entries_3_lf_lottie_life_coffee_1 = { "lottie_life_coffee_1.json": lf_lottie_life_coffee_1 };
import lf_lottie_life_drink_1 from "../lottie_assets/lottie_life_drink_1.json";
export const entries_3_lf_lottie_life_drink_1 = { "lottie_life_drink_1.json": lf_lottie_life_drink_1 };
import lf_lottie_life_earth_1 from "../lottie_assets/lottie_life_earth_1.json";
export const entries_3_lf_lottie_life_earth_1 = { "lottie_life_earth_1.json": lf_lottie_life_earth_1 };
import lf_lottie_life_fire_1 from "../lottie_assets/lottie_life_fire_1.json";
export const entries_3_lf_lottie_life_fire_1 = { "lottie_life_fire_1.json": lf_lottie_life_fire_1 };
import lf_lottie_life_fire_2 from "../lottie_assets/lottie_life_fire_2.json";
export const entries_3_lf_lottie_life_fire_2 = { "lottie_life_fire_2.json": lf_lottie_life_fire_2 };
import lf_lottie_life_fire_3 from "../lottie_assets/lottie_life_fire_3.json";
export const entries_3_lf_lottie_life_fire_3 = { "lottie_life_fire_3.json": lf_lottie_life_fire_3 };
import lf_lottie_life_fitness_1 from "../lottie_assets/lottie_life_fitness_1.json";
export const entries_3_lf_lottie_life_fitness_1 = { "lottie_life_fitness_1.json": lf_lottie_life_fitness_1 };
import lf_lottie_life_fitness_2 from "../lottie_assets/lottie_life_fitness_2.json";
export const entries_3_lf_lottie_life_fitness_2 = { "lottie_life_fitness_2.json": lf_lottie_life_fitness_2 };
import lf_lottie_life_globe_1 from "../lottie_assets/lottie_life_globe_1.json";
export const entries_3_lf_lottie_life_globe_1 = { "lottie_life_globe_1.json": lf_lottie_life_globe_1 };
import lf_lottie_life_globe_2 from "../lottie_assets/lottie_life_globe_2.json";
export const entries_3_lf_lottie_life_globe_2 = { "lottie_life_globe_2.json": lf_lottie_life_globe_2 };
import lf_lottie_life_globe_3 from "../lottie_assets/lottie_life_globe_3.json";
export const entries_3_lf_lottie_life_globe_3 = { "lottie_life_globe_3.json": lf_lottie_life_globe_3 };
import lf_lottie_life_globe_4 from "../lottie_assets/lottie_life_globe_4.json";
export const entries_3_lf_lottie_life_globe_4 = { "lottie_life_globe_4.json": lf_lottie_life_globe_4 };
import lf_lottie_life_globe_5 from "../lottie_assets/lottie_life_globe_5.json";
export const entries_3_lf_lottie_life_globe_5 = { "lottie_life_globe_5.json": lf_lottie_life_globe_5 };
import lf_lottie_life_idea_1 from "../lottie_assets/lottie_life_idea_1.json";
export const entries_3_lf_lottie_life_idea_1 = { "lottie_life_idea_1.json": lf_lottie_life_idea_1 };
import lf_lottie_life_idea_2 from "../lottie_assets/lottie_life_idea_2.json";
export const entries_3_lf_lottie_life_idea_2 = { "lottie_life_idea_2.json": lf_lottie_life_idea_2 };
import lf_lottie_life_idea_3 from "../lottie_assets/lottie_life_idea_3.json";
export const entries_3_lf_lottie_life_idea_3 = { "lottie_life_idea_3.json": lf_lottie_life_idea_3 };
import lf_lottie_life_location_1 from "../lottie_assets/lottie_life_location_1.json";
export const entries_3_lf_lottie_life_location_1 = { "lottie_life_location_1.json": lf_lottie_life_location_1 };
import lf_lottie_life_location_2 from "../lottie_assets/lottie_life_location_2.json";
export const entries_3_lf_lottie_life_location_2 = { "lottie_life_location_2.json": lf_lottie_life_location_2 };
import lf_lottie_life_location_3 from "../lottie_assets/lottie_life_location_3.json";
export const entries_3_lf_lottie_life_location_3 = { "lottie_life_location_3.json": lf_lottie_life_location_3 };
import lf_lottie_life_location_4 from "../lottie_assets/lottie_life_location_4.json";
export const entries_3_lf_lottie_life_location_4 = { "lottie_life_location_4.json": lf_lottie_life_location_4 };
import lf_lottie_life_location_5 from "../lottie_assets/lottie_life_location_5.json";
export const entries_3_lf_lottie_life_location_5 = { "lottie_life_location_5.json": lf_lottie_life_location_5 };
import lf_lottie_life_map_1 from "../lottie_assets/lottie_life_map_1.json";
export const entries_3_lf_lottie_life_map_1 = { "lottie_life_map_1.json": lf_lottie_life_map_1 };
import lf_lottie_life_map_2 from "../lottie_assets/lottie_life_map_2.json";
export const entries_3_lf_lottie_life_map_2 = { "lottie_life_map_2.json": lf_lottie_life_map_2 };
import lf_lottie_life_map_3 from "../lottie_assets/lottie_life_map_3.json";
export const entries_3_lf_lottie_life_map_3 = { "lottie_life_map_3.json": lf_lottie_life_map_3 };
import lf_lottie_life_map_4 from "../lottie_assets/lottie_life_map_4.json";
export const entries_3_lf_lottie_life_map_4 = { "lottie_life_map_4.json": lf_lottie_life_map_4 };
import lf_lottie_life_map_5 from "../lottie_assets/lottie_life_map_5.json";
export const entries_3_lf_lottie_life_map_5 = { "lottie_life_map_5.json": lf_lottie_life_map_5 };
import lf_lottie_life_pin_1 from "../lottie_assets/lottie_life_pin_1.json";
export const entries_3_lf_lottie_life_pin_1 = { "lottie_life_pin_1.json": lf_lottie_life_pin_1 };
import lf_lottie_life_pin_2 from "../lottie_assets/lottie_life_pin_2.json";
export const entries_3_lf_lottie_life_pin_2 = { "lottie_life_pin_2.json": lf_lottie_life_pin_2 };
import lf_lottie_life_pin_3 from "../lottie_assets/lottie_life_pin_3.json";
export const entries_3_lf_lottie_life_pin_3 = { "lottie_life_pin_3.json": lf_lottie_life_pin_3 };
import lf_lottie_life_pin_4 from "../lottie_assets/lottie_life_pin_4.json";
export const entries_3_lf_lottie_life_pin_4 = { "lottie_life_pin_4.json": lf_lottie_life_pin_4 };
