/* eslint-disable */
import lf_lottie_ui_settings_5 from "../lottie_assets/lottie_ui_settings_5.json";
export const entries_9_lf_lottie_ui_settings_5 = { "lottie_ui_settings_5.json": lf_lottie_ui_settings_5 };
import lf_lottie_ui_sync_1 from "../lottie_assets/lottie_ui_sync_1.json";
export const entries_9_lf_lottie_ui_sync_1 = { "lottie_ui_sync_1.json": lf_lottie_ui_sync_1 };
import lf_lottie_ui_sync_2 from "../lottie_assets/lottie_ui_sync_2.json";
export const entries_9_lf_lottie_ui_sync_2 = { "lottie_ui_sync_2.json": lf_lottie_ui_sync_2 };
import lf_lottie_ui_sync_3 from "../lottie_assets/lottie_ui_sync_3.json";
export const entries_9_lf_lottie_ui_sync_3 = { "lottie_ui_sync_3.json": lf_lottie_ui_sync_3 };
import lf_lottie_ui_time_1 from "../lottie_assets/lottie_ui_time_1.json";
export const entries_9_lf_lottie_ui_time_1 = { "lottie_ui_time_1.json": lf_lottie_ui_time_1 };
import lf_lottie_ui_time_2 from "../lottie_assets/lottie_ui_time_2.json";
export const entries_9_lf_lottie_ui_time_2 = { "lottie_ui_time_2.json": lf_lottie_ui_time_2 };
import lf_lottie_ui_time_3 from "../lottie_assets/lottie_ui_time_3.json";
export const entries_9_lf_lottie_ui_time_3 = { "lottie_ui_time_3.json": lf_lottie_ui_time_3 };
import lf_lottie_ui_trash_1 from "../lottie_assets/lottie_ui_trash_1.json";
export const entries_9_lf_lottie_ui_trash_1 = { "lottie_ui_trash_1.json": lf_lottie_ui_trash_1 };
import lf_lottie_ui_trash_2 from "../lottie_assets/lottie_ui_trash_2.json";
export const entries_9_lf_lottie_ui_trash_2 = { "lottie_ui_trash_2.json": lf_lottie_ui_trash_2 };
import lf_lottie_ui_trash_3 from "../lottie_assets/lottie_ui_trash_3.json";
export const entries_9_lf_lottie_ui_trash_3 = { "lottie_ui_trash_3.json": lf_lottie_ui_trash_3 };
import lf_lottie_ui_trash_4 from "../lottie_assets/lottie_ui_trash_4.json";
export const entries_9_lf_lottie_ui_trash_4 = { "lottie_ui_trash_4.json": lf_lottie_ui_trash_4 };
import lf_lottie_ui_trash_5 from "../lottie_assets/lottie_ui_trash_5.json";
export const entries_9_lf_lottie_ui_trash_5 = { "lottie_ui_trash_5.json": lf_lottie_ui_trash_5 };
import lf_lottie_ui_upload_1 from "../lottie_assets/lottie_ui_upload_1.json";
export const entries_9_lf_lottie_ui_upload_1 = { "lottie_ui_upload_1.json": lf_lottie_ui_upload_1 };
import lf_lottie_ui_upload_2 from "../lottie_assets/lottie_ui_upload_2.json";
export const entries_9_lf_lottie_ui_upload_2 = { "lottie_ui_upload_2.json": lf_lottie_ui_upload_2 };
import lf_lottie_ui_upload_3 from "../lottie_assets/lottie_ui_upload_3.json";
export const entries_9_lf_lottie_ui_upload_3 = { "lottie_ui_upload_3.json": lf_lottie_ui_upload_3 };
import lf_lottie_ui_upload_4 from "../lottie_assets/lottie_ui_upload_4.json";
export const entries_9_lf_lottie_ui_upload_4 = { "lottie_ui_upload_4.json": lf_lottie_ui_upload_4 };
import lf_lottie_ui_upload_5 from "../lottie_assets/lottie_ui_upload_5.json";
export const entries_9_lf_lottie_ui_upload_5 = { "lottie_ui_upload_5.json": lf_lottie_ui_upload_5 };
import lf_lottie_ui_warning_1 from "../lottie_assets/lottie_ui_warning_1.json";
export const entries_9_lf_lottie_ui_warning_1 = { "lottie_ui_warning_1.json": lf_lottie_ui_warning_1 };
import lf_lottie_ui_warning_2 from "../lottie_assets/lottie_ui_warning_2.json";
export const entries_9_lf_lottie_ui_warning_2 = { "lottie_ui_warning_2.json": lf_lottie_ui_warning_2 };
import lf_lottie_ui_warning_3 from "../lottie_assets/lottie_ui_warning_3.json";
export const entries_9_lf_lottie_ui_warning_3 = { "lottie_ui_warning_3.json": lf_lottie_ui_warning_3 };
import lf_lottie_ui_warning_4 from "../lottie_assets/lottie_ui_warning_4.json";
export const entries_9_lf_lottie_ui_warning_4 = { "lottie_ui_warning_4.json": lf_lottie_ui_warning_4 };
import lf_lottie_ui_warning_5 from "../lottie_assets/lottie_ui_warning_5.json";
export const entries_9_lf_lottie_ui_warning_5 = { "lottie_ui_warning_5.json": lf_lottie_ui_warning_5 };
import lf_sparkles from "../lottie_assets/sparkles.json";
export const entries_9_lf_sparkles = { "sparkles.json": lf_sparkles };
import lf_ui_animate_tab_animate_tab_1 from "../lottie_assets/ui_animate_tab_animate_tab_1.json";
export const entries_9_lf_ui_animate_tab_animate_tab_1 = { "ui_animate_tab_animate_tab_1.json": lf_ui_animate_tab_animate_tab_1 };
import lf_ui_animate_tab_animate_tab_1_example from "../lottie_assets/ui_animate_tab_animate_tab_1_example.json";
export const entries_9_lf_ui_animate_tab_animate_tab_1_example = { "ui_animate_tab_animate_tab_1_example.json": lf_ui_animate_tab_animate_tab_1_example };
import lf_ui_floating_action_button_ic_fab_animate from "../lottie_assets/ui_floating_action_button_ic_fab_animate.json";
export const entries_9_lf_ui_floating_action_button_ic_fab_animate = { "ui_floating_action_button_ic_fab_animate.json": lf_ui_floating_action_button_ic_fab_animate };
import lf_ui_ic_fav_ic_fav from "../lottie_assets/ui_ic_fav_ic_fav.json";
export const entries_9_lf_ui_ic_fav_ic_fav = { "ui_ic_fav_ic_fav.json": lf_ui_ic_fav_ic_fav };
import lf_ui_pagination_indicator_pagination_indicator from "../lottie_assets/ui_pagination_indicator_pagination_indicator.json";
export const entries_9_lf_ui_pagination_indicator_pagination_indicator = { "ui_pagination_indicator_pagination_indicator.json": lf_ui_pagination_indicator_pagination_indicator };
import lf_weather_clear_day from "../lottie_assets/weather_clear_day.json";
export const entries_9_lf_weather_clear_day = { "weather_clear_day.json": lf_weather_clear_day };
import lf_weather_clear_night from "../lottie_assets/weather_clear_night.json";
export const entries_9_lf_weather_clear_night = { "weather_clear_night.json": lf_weather_clear_night };
import lf_weather_cloudy from "../lottie_assets/weather_cloudy.json";
export const entries_9_lf_weather_cloudy = { "weather_cloudy.json": lf_weather_cloudy };
import lf_weather_fog from "../lottie_assets/weather_fog.json";
export const entries_9_lf_weather_fog = { "weather_fog.json": lf_weather_fog };
import lf_weather_hail from "../lottie_assets/weather_hail.json";
export const entries_9_lf_weather_hail = { "weather_hail.json": lf_weather_hail };
import lf_weather_hurricane from "../lottie_assets/weather_hurricane.json";
export const entries_9_lf_weather_hurricane = { "weather_hurricane.json": lf_weather_hurricane };
import lf_weather_mist from "../lottie_assets/weather_mist.json";
export const entries_9_lf_weather_mist = { "weather_mist.json": lf_weather_mist };
import lf_weather_rain from "../lottie_assets/weather_rain.json";
export const entries_9_lf_weather_rain = { "weather_rain.json": lf_weather_rain };
import lf_weather_snow from "../lottie_assets/weather_snow.json";
export const entries_9_lf_weather_snow = { "weather_snow.json": lf_weather_snow };
import lf_weather_snowflake from "../lottie_assets/weather_snowflake.json";
export const entries_9_lf_weather_snowflake = { "weather_snowflake.json": lf_weather_snowflake };
import lf_weather_sunrise from "../lottie_assets/weather_sunrise.json";
export const entries_9_lf_weather_sunrise = { "weather_sunrise.json": lf_weather_sunrise };
import lf_weather_sunset from "../lottie_assets/weather_sunset.json";
export const entries_9_lf_weather_sunset = { "weather_sunset.json": lf_weather_sunset };
import lf_weather_thermometer from "../lottie_assets/weather_thermometer.json";
export const entries_9_lf_weather_thermometer = { "weather_thermometer.json": lf_weather_thermometer };
import lf_weather_thunderstorms from "../lottie_assets/weather_thunderstorms.json";
export const entries_9_lf_weather_thunderstorms = { "weather_thunderstorms.json": lf_weather_thunderstorms };
import lf_weather_thunderstorms_rain from "../lottie_assets/weather_thunderstorms_rain.json";
export const entries_9_lf_weather_thunderstorms_rain = { "weather_thunderstorms_rain.json": lf_weather_thunderstorms_rain };
import lf_weather_tornado from "../lottie_assets/weather_tornado.json";
export const entries_9_lf_weather_tornado = { "weather_tornado.json": lf_weather_tornado };
import lf_weather_wind from "../lottie_assets/weather_wind.json";
export const entries_9_lf_weather_wind = { "weather_wind.json": lf_weather_wind };
