/* eslint-disable */
import lf_lottie_interact_bell_2 from "../lottie_assets/lottie_interact_bell_2.json";
export const entries_2_lf_lottie_interact_bell_2 = { "lottie_interact_bell_2.json": lf_lottie_interact_bell_2 };
import lf_lottie_interact_bell_3 from "../lottie_assets/lottie_interact_bell_3.json";
export const entries_2_lf_lottie_interact_bell_3 = { "lottie_interact_bell_3.json": lf_lottie_interact_bell_3 };
import lf_lottie_interact_bell_4 from "../lottie_assets/lottie_interact_bell_4.json";
export const entries_2_lf_lottie_interact_bell_4 = { "lottie_interact_bell_4.json": lf_lottie_interact_bell_4 };
import lf_lottie_interact_bell_5 from "../lottie_assets/lottie_interact_bell_5.json";
export const entries_2_lf_lottie_interact_bell_5 = { "lottie_interact_bell_5.json": lf_lottie_interact_bell_5 };
import lf_lottie_interact_bookmark_1 from "../lottie_assets/lottie_interact_bookmark_1.json";
export const entries_2_lf_lottie_interact_bookmark_1 = { "lottie_interact_bookmark_1.json": lf_lottie_interact_bookmark_1 };
import lf_lottie_interact_bookmark_2 from "../lottie_assets/lottie_interact_bookmark_2.json";
export const entries_2_lf_lottie_interact_bookmark_2 = { "lottie_interact_bookmark_2.json": lf_lottie_interact_bookmark_2 };
import lf_lottie_interact_bookmark_3 from "../lottie_assets/lottie_interact_bookmark_3.json";
export const entries_2_lf_lottie_interact_bookmark_3 = { "lottie_interact_bookmark_3.json": lf_lottie_interact_bookmark_3 };
import lf_lottie_interact_bookmark_4 from "../lottie_assets/lottie_interact_bookmark_4.json";
export const entries_2_lf_lottie_interact_bookmark_4 = { "lottie_interact_bookmark_4.json": lf_lottie_interact_bookmark_4 };
import lf_lottie_interact_bookmark_5 from "../lottie_assets/lottie_interact_bookmark_5.json";
export const entries_2_lf_lottie_interact_bookmark_5 = { "lottie_interact_bookmark_5.json": lf_lottie_interact_bookmark_5 };
import lf_lottie_interact_chat_1 from "../lottie_assets/lottie_interact_chat_1.json";
export const entries_2_lf_lottie_interact_chat_1 = { "lottie_interact_chat_1.json": lf_lottie_interact_chat_1 };
import lf_lottie_interact_chat_2 from "../lottie_assets/lottie_interact_chat_2.json";
export const entries_2_lf_lottie_interact_chat_2 = { "lottie_interact_chat_2.json": lf_lottie_interact_chat_2 };
import lf_lottie_interact_chat_3 from "../lottie_assets/lottie_interact_chat_3.json";
export const entries_2_lf_lottie_interact_chat_3 = { "lottie_interact_chat_3.json": lf_lottie_interact_chat_3 };
import lf_lottie_interact_chat_4 from "../lottie_assets/lottie_interact_chat_4.json";
export const entries_2_lf_lottie_interact_chat_4 = { "lottie_interact_chat_4.json": lf_lottie_interact_chat_4 };
import lf_lottie_interact_chat_5 from "../lottie_assets/lottie_interact_chat_5.json";
export const entries_2_lf_lottie_interact_chat_5 = { "lottie_interact_chat_5.json": lf_lottie_interact_chat_5 };
import lf_lottie_interact_comment_1 from "../lottie_assets/lottie_interact_comment_1.json";
export const entries_2_lf_lottie_interact_comment_1 = { "lottie_interact_comment_1.json": lf_lottie_interact_comment_1 };
import lf_lottie_interact_comment_2 from "../lottie_assets/lottie_interact_comment_2.json";
export const entries_2_lf_lottie_interact_comment_2 = { "lottie_interact_comment_2.json": lf_lottie_interact_comment_2 };
import lf_lottie_interact_comment_3 from "../lottie_assets/lottie_interact_comment_3.json";
export const entries_2_lf_lottie_interact_comment_3 = { "lottie_interact_comment_3.json": lf_lottie_interact_comment_3 };
import lf_lottie_interact_comment_4 from "../lottie_assets/lottie_interact_comment_4.json";
export const entries_2_lf_lottie_interact_comment_4 = { "lottie_interact_comment_4.json": lf_lottie_interact_comment_4 };
import lf_lottie_interact_heart_1 from "../lottie_assets/lottie_interact_heart_1.json";
export const entries_2_lf_lottie_interact_heart_1 = { "lottie_interact_heart_1.json": lf_lottie_interact_heart_1 };
import lf_lottie_interact_heart_2 from "../lottie_assets/lottie_interact_heart_2.json";
export const entries_2_lf_lottie_interact_heart_2 = { "lottie_interact_heart_2.json": lf_lottie_interact_heart_2 };
import lf_lottie_interact_heart_3 from "../lottie_assets/lottie_interact_heart_3.json";
export const entries_2_lf_lottie_interact_heart_3 = { "lottie_interact_heart_3.json": lf_lottie_interact_heart_3 };
import lf_lottie_interact_heart_4 from "../lottie_assets/lottie_interact_heart_4.json";
export const entries_2_lf_lottie_interact_heart_4 = { "lottie_interact_heart_4.json": lf_lottie_interact_heart_4 };
import lf_lottie_interact_heart_5 from "../lottie_assets/lottie_interact_heart_5.json";
export const entries_2_lf_lottie_interact_heart_5 = { "lottie_interact_heart_5.json": lf_lottie_interact_heart_5 };
import lf_lottie_interact_like_1 from "../lottie_assets/lottie_interact_like_1.json";
export const entries_2_lf_lottie_interact_like_1 = { "lottie_interact_like_1.json": lf_lottie_interact_like_1 };
import lf_lottie_interact_like_2 from "../lottie_assets/lottie_interact_like_2.json";
export const entries_2_lf_lottie_interact_like_2 = { "lottie_interact_like_2.json": lf_lottie_interact_like_2 };
import lf_lottie_interact_like_3 from "../lottie_assets/lottie_interact_like_3.json";
export const entries_2_lf_lottie_interact_like_3 = { "lottie_interact_like_3.json": lf_lottie_interact_like_3 };
import lf_lottie_interact_like_4 from "../lottie_assets/lottie_interact_like_4.json";
export const entries_2_lf_lottie_interact_like_4 = { "lottie_interact_like_4.json": lf_lottie_interact_like_4 };
import lf_lottie_interact_like_5 from "../lottie_assets/lottie_interact_like_5.json";
export const entries_2_lf_lottie_interact_like_5 = { "lottie_interact_like_5.json": lf_lottie_interact_like_5 };
import lf_lottie_interact_mail_1 from "../lottie_assets/lottie_interact_mail_1.json";
export const entries_2_lf_lottie_interact_mail_1 = { "lottie_interact_mail_1.json": lf_lottie_interact_mail_1 };
import lf_lottie_interact_mail_2 from "../lottie_assets/lottie_interact_mail_2.json";
export const entries_2_lf_lottie_interact_mail_2 = { "lottie_interact_mail_2.json": lf_lottie_interact_mail_2 };
import lf_lottie_interact_mail_3 from "../lottie_assets/lottie_interact_mail_3.json";
export const entries_2_lf_lottie_interact_mail_3 = { "lottie_interact_mail_3.json": lf_lottie_interact_mail_3 };
import lf_lottie_interact_mail_4 from "../lottie_assets/lottie_interact_mail_4.json";
export const entries_2_lf_lottie_interact_mail_4 = { "lottie_interact_mail_4.json": lf_lottie_interact_mail_4 };
import lf_lottie_interact_mail_5 from "../lottie_assets/lottie_interact_mail_5.json";
export const entries_2_lf_lottie_interact_mail_5 = { "lottie_interact_mail_5.json": lf_lottie_interact_mail_5 };
import lf_lottie_interact_message_1 from "../lottie_assets/lottie_interact_message_1.json";
export const entries_2_lf_lottie_interact_message_1 = { "lottie_interact_message_1.json": lf_lottie_interact_message_1 };
import lf_lottie_interact_message_2 from "../lottie_assets/lottie_interact_message_2.json";
export const entries_2_lf_lottie_interact_message_2 = { "lottie_interact_message_2.json": lf_lottie_interact_message_2 };
import lf_lottie_interact_message_3 from "../lottie_assets/lottie_interact_message_3.json";
export const entries_2_lf_lottie_interact_message_3 = { "lottie_interact_message_3.json": lf_lottie_interact_message_3 };
import lf_lottie_interact_message_4 from "../lottie_assets/lottie_interact_message_4.json";
export const entries_2_lf_lottie_interact_message_4 = { "lottie_interact_message_4.json": lf_lottie_interact_message_4 };
import lf_lottie_interact_message_5 from "../lottie_assets/lottie_interact_message_5.json";
export const entries_2_lf_lottie_interact_message_5 = { "lottie_interact_message_5.json": lf_lottie_interact_message_5 };
import lf_lottie_interact_phone_1 from "../lottie_assets/lottie_interact_phone_1.json";
export const entries_2_lf_lottie_interact_phone_1 = { "lottie_interact_phone_1.json": lf_lottie_interact_phone_1 };
import lf_lottie_interact_phone_2 from "../lottie_assets/lottie_interact_phone_2.json";
export const entries_2_lf_lottie_interact_phone_2 = { "lottie_interact_phone_2.json": lf_lottie_interact_phone_2 };
import lf_lottie_interact_phone_3 from "../lottie_assets/lottie_interact_phone_3.json";
export const entries_2_lf_lottie_interact_phone_3 = { "lottie_interact_phone_3.json": lf_lottie_interact_phone_3 };
import lf_lottie_interact_phone_4 from "../lottie_assets/lottie_interact_phone_4.json";
export const entries_2_lf_lottie_interact_phone_4 = { "lottie_interact_phone_4.json": lf_lottie_interact_phone_4 };
import lf_lottie_interact_phone_5 from "../lottie_assets/lottie_interact_phone_5.json";
export const entries_2_lf_lottie_interact_phone_5 = { "lottie_interact_phone_5.json": lf_lottie_interact_phone_5 };
import lf_lottie_interact_send_1 from "../lottie_assets/lottie_interact_send_1.json";
export const entries_2_lf_lottie_interact_send_1 = { "lottie_interact_send_1.json": lf_lottie_interact_send_1 };
import lf_lottie_interact_share_1 from "../lottie_assets/lottie_interact_share_1.json";
export const entries_2_lf_lottie_interact_share_1 = { "lottie_interact_share_1.json": lf_lottie_interact_share_1 };
import lf_lottie_interact_share_2 from "../lottie_assets/lottie_interact_share_2.json";
export const entries_2_lf_lottie_interact_share_2 = { "lottie_interact_share_2.json": lf_lottie_interact_share_2 };
import lf_lottie_interact_share_3 from "../lottie_assets/lottie_interact_share_3.json";
export const entries_2_lf_lottie_interact_share_3 = { "lottie_interact_share_3.json": lf_lottie_interact_share_3 };
import lf_lottie_interact_share_4 from "../lottie_assets/lottie_interact_share_4.json";
export const entries_2_lf_lottie_interact_share_4 = { "lottie_interact_share_4.json": lf_lottie_interact_share_4 };
