/* eslint-disable */
import lf_lottie_tech_wifi_4 from "../lottie_assets/lottie_tech_wifi_4.json";
export const entries_7_lf_lottie_tech_wifi_4 = { "lottie_tech_wifi_4.json": lf_lottie_tech_wifi_4 };
import lf_lottie_tech_wifi_5 from "../lottie_assets/lottie_tech_wifi_5.json";
export const entries_7_lf_lottie_tech_wifi_5 = { "lottie_tech_wifi_5.json": lf_lottie_tech_wifi_5 };
import lf_lottie_ui_add_1 from "../lottie_assets/lottie_ui_add_1.json";
export const entries_7_lf_lottie_ui_add_1 = { "lottie_ui_add_1.json": lf_lottie_ui_add_1 };
import lf_lottie_ui_add_2 from "../lottie_assets/lottie_ui_add_2.json";
export const entries_7_lf_lottie_ui_add_2 = { "lottie_ui_add_2.json": lf_lottie_ui_add_2 };
import lf_lottie_ui_add_3 from "../lottie_assets/lottie_ui_add_3.json";
export const entries_7_lf_lottie_ui_add_3 = { "lottie_ui_add_3.json": lf_lottie_ui_add_3 };
import lf_lottie_ui_add_4 from "../lottie_assets/lottie_ui_add_4.json";
export const entries_7_lf_lottie_ui_add_4 = { "lottie_ui_add_4.json": lf_lottie_ui_add_4 };
import lf_lottie_ui_add_5 from "../lottie_assets/lottie_ui_add_5.json";
export const entries_7_lf_lottie_ui_add_5 = { "lottie_ui_add_5.json": lf_lottie_ui_add_5 };
import lf_lottie_ui_alert_1 from "../lottie_assets/lottie_ui_alert_1.json";
export const entries_7_lf_lottie_ui_alert_1 = { "lottie_ui_alert_1.json": lf_lottie_ui_alert_1 };
import lf_lottie_ui_alert_2 from "../lottie_assets/lottie_ui_alert_2.json";
export const entries_7_lf_lottie_ui_alert_2 = { "lottie_ui_alert_2.json": lf_lottie_ui_alert_2 };
import lf_lottie_ui_alert_3 from "../lottie_assets/lottie_ui_alert_3.json";
export const entries_7_lf_lottie_ui_alert_3 = { "lottie_ui_alert_3.json": lf_lottie_ui_alert_3 };
import lf_lottie_ui_alert_4 from "../lottie_assets/lottie_ui_alert_4.json";
export const entries_7_lf_lottie_ui_alert_4 = { "lottie_ui_alert_4.json": lf_lottie_ui_alert_4 };
import lf_lottie_ui_calendar_1 from "../lottie_assets/lottie_ui_calendar_1.json";
export const entries_7_lf_lottie_ui_calendar_1 = { "lottie_ui_calendar_1.json": lf_lottie_ui_calendar_1 };
import lf_lottie_ui_calendar_2 from "../lottie_assets/lottie_ui_calendar_2.json";
export const entries_7_lf_lottie_ui_calendar_2 = { "lottie_ui_calendar_2.json": lf_lottie_ui_calendar_2 };
import lf_lottie_ui_calendar_3 from "../lottie_assets/lottie_ui_calendar_3.json";
export const entries_7_lf_lottie_ui_calendar_3 = { "lottie_ui_calendar_3.json": lf_lottie_ui_calendar_3 };
import lf_lottie_ui_calendar_4 from "../lottie_assets/lottie_ui_calendar_4.json";
export const entries_7_lf_lottie_ui_calendar_4 = { "lottie_ui_calendar_4.json": lf_lottie_ui_calendar_4 };
import lf_lottie_ui_calendar_5 from "../lottie_assets/lottie_ui_calendar_5.json";
export const entries_7_lf_lottie_ui_calendar_5 = { "lottie_ui_calendar_5.json": lf_lottie_ui_calendar_5 };
import lf_lottie_ui_check_1 from "../lottie_assets/lottie_ui_check_1.json";
export const entries_7_lf_lottie_ui_check_1 = { "lottie_ui_check_1.json": lf_lottie_ui_check_1 };
import lf_lottie_ui_check_2 from "../lottie_assets/lottie_ui_check_2.json";
export const entries_7_lf_lottie_ui_check_2 = { "lottie_ui_check_2.json": lf_lottie_ui_check_2 };
import lf_lottie_ui_check_3 from "../lottie_assets/lottie_ui_check_3.json";
export const entries_7_lf_lottie_ui_check_3 = { "lottie_ui_check_3.json": lf_lottie_ui_check_3 };
import lf_lottie_ui_check_4 from "../lottie_assets/lottie_ui_check_4.json";
export const entries_7_lf_lottie_ui_check_4 = { "lottie_ui_check_4.json": lf_lottie_ui_check_4 };
import lf_lottie_ui_check_5 from "../lottie_assets/lottie_ui_check_5.json";
export const entries_7_lf_lottie_ui_check_5 = { "lottie_ui_check_5.json": lf_lottie_ui_check_5 };
import lf_lottie_ui_close_1 from "../lottie_assets/lottie_ui_close_1.json";
export const entries_7_lf_lottie_ui_close_1 = { "lottie_ui_close_1.json": lf_lottie_ui_close_1 };
import lf_lottie_ui_close_2 from "../lottie_assets/lottie_ui_close_2.json";
export const entries_7_lf_lottie_ui_close_2 = { "lottie_ui_close_2.json": lf_lottie_ui_close_2 };
import lf_lottie_ui_close_3 from "../lottie_assets/lottie_ui_close_3.json";
export const entries_7_lf_lottie_ui_close_3 = { "lottie_ui_close_3.json": lf_lottie_ui_close_3 };
import lf_lottie_ui_close_4 from "../lottie_assets/lottie_ui_close_4.json";
export const entries_7_lf_lottie_ui_close_4 = { "lottie_ui_close_4.json": lf_lottie_ui_close_4 };
import lf_lottie_ui_delete_1 from "../lottie_assets/lottie_ui_delete_1.json";
export const entries_7_lf_lottie_ui_delete_1 = { "lottie_ui_delete_1.json": lf_lottie_ui_delete_1 };
import lf_lottie_ui_delete_2 from "../lottie_assets/lottie_ui_delete_2.json";
export const entries_7_lf_lottie_ui_delete_2 = { "lottie_ui_delete_2.json": lf_lottie_ui_delete_2 };
import lf_lottie_ui_delete_3 from "../lottie_assets/lottie_ui_delete_3.json";
export const entries_7_lf_lottie_ui_delete_3 = { "lottie_ui_delete_3.json": lf_lottie_ui_delete_3 };
import lf_lottie_ui_delete_4 from "../lottie_assets/lottie_ui_delete_4.json";
export const entries_7_lf_lottie_ui_delete_4 = { "lottie_ui_delete_4.json": lf_lottie_ui_delete_4 };
import lf_lottie_ui_download_1 from "../lottie_assets/lottie_ui_download_1.json";
export const entries_7_lf_lottie_ui_download_1 = { "lottie_ui_download_1.json": lf_lottie_ui_download_1 };
import lf_lottie_ui_download_2 from "../lottie_assets/lottie_ui_download_2.json";
export const entries_7_lf_lottie_ui_download_2 = { "lottie_ui_download_2.json": lf_lottie_ui_download_2 };
import lf_lottie_ui_download_3 from "../lottie_assets/lottie_ui_download_3.json";
export const entries_7_lf_lottie_ui_download_3 = { "lottie_ui_download_3.json": lf_lottie_ui_download_3 };
import lf_lottie_ui_download_4 from "../lottie_assets/lottie_ui_download_4.json";
export const entries_7_lf_lottie_ui_download_4 = { "lottie_ui_download_4.json": lf_lottie_ui_download_4 };
import lf_lottie_ui_download_5 from "../lottie_assets/lottie_ui_download_5.json";
export const entries_7_lf_lottie_ui_download_5 = { "lottie_ui_download_5.json": lf_lottie_ui_download_5 };
import lf_lottie_ui_edit_1 from "../lottie_assets/lottie_ui_edit_1.json";
export const entries_7_lf_lottie_ui_edit_1 = { "lottie_ui_edit_1.json": lf_lottie_ui_edit_1 };
import lf_lottie_ui_edit_2 from "../lottie_assets/lottie_ui_edit_2.json";
export const entries_7_lf_lottie_ui_edit_2 = { "lottie_ui_edit_2.json": lf_lottie_ui_edit_2 };
import lf_lottie_ui_edit_3 from "../lottie_assets/lottie_ui_edit_3.json";
export const entries_7_lf_lottie_ui_edit_3 = { "lottie_ui_edit_3.json": lf_lottie_ui_edit_3 };
import lf_lottie_ui_edit_4 from "../lottie_assets/lottie_ui_edit_4.json";
export const entries_7_lf_lottie_ui_edit_4 = { "lottie_ui_edit_4.json": lf_lottie_ui_edit_4 };
import lf_lottie_ui_edit_5 from "../lottie_assets/lottie_ui_edit_5.json";
export const entries_7_lf_lottie_ui_edit_5 = { "lottie_ui_edit_5.json": lf_lottie_ui_edit_5 };
import lf_lottie_ui_error_1 from "../lottie_assets/lottie_ui_error_1.json";
export const entries_7_lf_lottie_ui_error_1 = { "lottie_ui_error_1.json": lf_lottie_ui_error_1 };
import lf_lottie_ui_error_2 from "../lottie_assets/lottie_ui_error_2.json";
export const entries_7_lf_lottie_ui_error_2 = { "lottie_ui_error_2.json": lf_lottie_ui_error_2 };
import lf_lottie_ui_error_3 from "../lottie_assets/lottie_ui_error_3.json";
export const entries_7_lf_lottie_ui_error_3 = { "lottie_ui_error_3.json": lf_lottie_ui_error_3 };
import lf_lottie_ui_error_4 from "../lottie_assets/lottie_ui_error_4.json";
export const entries_7_lf_lottie_ui_error_4 = { "lottie_ui_error_4.json": lf_lottie_ui_error_4 };
import lf_lottie_ui_error_5 from "../lottie_assets/lottie_ui_error_5.json";
export const entries_7_lf_lottie_ui_error_5 = { "lottie_ui_error_5.json": lf_lottie_ui_error_5 };
import lf_lottie_ui_filter_1 from "../lottie_assets/lottie_ui_filter_1.json";
export const entries_7_lf_lottie_ui_filter_1 = { "lottie_ui_filter_1.json": lf_lottie_ui_filter_1 };
import lf_lottie_ui_filter_2 from "../lottie_assets/lottie_ui_filter_2.json";
export const entries_7_lf_lottie_ui_filter_2 = { "lottie_ui_filter_2.json": lf_lottie_ui_filter_2 };
import lf_lottie_ui_filter_3 from "../lottie_assets/lottie_ui_filter_3.json";
export const entries_7_lf_lottie_ui_filter_3 = { "lottie_ui_filter_3.json": lf_lottie_ui_filter_3 };
import lf_lottie_ui_filter_4 from "../lottie_assets/lottie_ui_filter_4.json";
export const entries_7_lf_lottie_ui_filter_4 = { "lottie_ui_filter_4.json": lf_lottie_ui_filter_4 };
