/* eslint-disable */
import lf_lottie_biz_chart_2 from "../lottie_assets/lottie_biz_chart_2.json";
export const entries_1_lf_lottie_biz_chart_2 = { "lottie_biz_chart_2.json": lf_lottie_biz_chart_2 };
import lf_lottie_biz_chart_3 from "../lottie_assets/lottie_biz_chart_3.json";
export const entries_1_lf_lottie_biz_chart_3 = { "lottie_biz_chart_3.json": lf_lottie_biz_chart_3 };
import lf_lottie_biz_chart_4 from "../lottie_assets/lottie_biz_chart_4.json";
export const entries_1_lf_lottie_biz_chart_4 = { "lottie_biz_chart_4.json": lf_lottie_biz_chart_4 };
import lf_lottie_biz_chart_5 from "../lottie_assets/lottie_biz_chart_5.json";
export const entries_1_lf_lottie_biz_chart_5 = { "lottie_biz_chart_5.json": lf_lottie_biz_chart_5 };
import lf_lottie_biz_coin_1 from "../lottie_assets/lottie_biz_coin_1.json";
export const entries_1_lf_lottie_biz_coin_1 = { "lottie_biz_coin_1.json": lf_lottie_biz_coin_1 };
import lf_lottie_biz_coin_2 from "../lottie_assets/lottie_biz_coin_2.json";
export const entries_1_lf_lottie_biz_coin_2 = { "lottie_biz_coin_2.json": lf_lottie_biz_coin_2 };
import lf_lottie_biz_coin_3 from "../lottie_assets/lottie_biz_coin_3.json";
export const entries_1_lf_lottie_biz_coin_3 = { "lottie_biz_coin_3.json": lf_lottie_biz_coin_3 };
import lf_lottie_biz_coin_4 from "../lottie_assets/lottie_biz_coin_4.json";
export const entries_1_lf_lottie_biz_coin_4 = { "lottie_biz_coin_4.json": lf_lottie_biz_coin_4 };
import lf_lottie_biz_coin_5 from "../lottie_assets/lottie_biz_coin_5.json";
export const entries_1_lf_lottie_biz_coin_5 = { "lottie_biz_coin_5.json": lf_lottie_biz_coin_5 };
import lf_lottie_biz_crown_1 from "../lottie_assets/lottie_biz_crown_1.json";
export const entries_1_lf_lottie_biz_crown_1 = { "lottie_biz_crown_1.json": lf_lottie_biz_crown_1 };
import lf_lottie_biz_crown_2 from "../lottie_assets/lottie_biz_crown_2.json";
export const entries_1_lf_lottie_biz_crown_2 = { "lottie_biz_crown_2.json": lf_lottie_biz_crown_2 };
import lf_lottie_biz_delivery_1 from "../lottie_assets/lottie_biz_delivery_1.json";
export const entries_1_lf_lottie_biz_delivery_1 = { "lottie_biz_delivery_1.json": lf_lottie_biz_delivery_1 };
import lf_lottie_biz_dollar_1 from "../lottie_assets/lottie_biz_dollar_1.json";
export const entries_1_lf_lottie_biz_dollar_1 = { "lottie_biz_dollar_1.json": lf_lottie_biz_dollar_1 };
import lf_lottie_biz_dollar_2 from "../lottie_assets/lottie_biz_dollar_2.json";
export const entries_1_lf_lottie_biz_dollar_2 = { "lottie_biz_dollar_2.json": lf_lottie_biz_dollar_2 };
import lf_lottie_biz_dollar_3 from "../lottie_assets/lottie_biz_dollar_3.json";
export const entries_1_lf_lottie_biz_dollar_3 = { "lottie_biz_dollar_3.json": lf_lottie_biz_dollar_3 };
import lf_lottie_biz_gift_1 from "../lottie_assets/lottie_biz_gift_1.json";
export const entries_1_lf_lottie_biz_gift_1 = { "lottie_biz_gift_1.json": lf_lottie_biz_gift_1 };
import lf_lottie_biz_gift_2 from "../lottie_assets/lottie_biz_gift_2.json";
export const entries_1_lf_lottie_biz_gift_2 = { "lottie_biz_gift_2.json": lf_lottie_biz_gift_2 };
import lf_lottie_biz_gift_3 from "../lottie_assets/lottie_biz_gift_3.json";
export const entries_1_lf_lottie_biz_gift_3 = { "lottie_biz_gift_3.json": lf_lottie_biz_gift_3 };
import lf_lottie_biz_gift_4 from "../lottie_assets/lottie_biz_gift_4.json";
export const entries_1_lf_lottie_biz_gift_4 = { "lottie_biz_gift_4.json": lf_lottie_biz_gift_4 };
import lf_lottie_biz_graph_1 from "../lottie_assets/lottie_biz_graph_1.json";
export const entries_1_lf_lottie_biz_graph_1 = { "lottie_biz_graph_1.json": lf_lottie_biz_graph_1 };
import lf_lottie_biz_graph_2 from "../lottie_assets/lottie_biz_graph_2.json";
export const entries_1_lf_lottie_biz_graph_2 = { "lottie_biz_graph_2.json": lf_lottie_biz_graph_2 };
import lf_lottie_biz_graph_3 from "../lottie_assets/lottie_biz_graph_3.json";
export const entries_1_lf_lottie_biz_graph_3 = { "lottie_biz_graph_3.json": lf_lottie_biz_graph_3 };
import lf_lottie_biz_money_1 from "../lottie_assets/lottie_biz_money_1.json";
export const entries_1_lf_lottie_biz_money_1 = { "lottie_biz_money_1.json": lf_lottie_biz_money_1 };
import lf_lottie_biz_shop_1 from "../lottie_assets/lottie_biz_shop_1.json";
export const entries_1_lf_lottie_biz_shop_1 = { "lottie_biz_shop_1.json": lf_lottie_biz_shop_1 };
import lf_lottie_biz_shop_2 from "../lottie_assets/lottie_biz_shop_2.json";
export const entries_1_lf_lottie_biz_shop_2 = { "lottie_biz_shop_2.json": lf_lottie_biz_shop_2 };
import lf_lottie_biz_shop_3 from "../lottie_assets/lottie_biz_shop_3.json";
export const entries_1_lf_lottie_biz_shop_3 = { "lottie_biz_shop_3.json": lf_lottie_biz_shop_3 };
import lf_lottie_biz_shop_4 from "../lottie_assets/lottie_biz_shop_4.json";
export const entries_1_lf_lottie_biz_shop_4 = { "lottie_biz_shop_4.json": lf_lottie_biz_shop_4 };
import lf_lottie_biz_shop_5 from "../lottie_assets/lottie_biz_shop_5.json";
export const entries_1_lf_lottie_biz_shop_5 = { "lottie_biz_shop_5.json": lf_lottie_biz_shop_5 };
import lf_lottie_biz_target_1 from "../lottie_assets/lottie_biz_target_1.json";
export const entries_1_lf_lottie_biz_target_1 = { "lottie_biz_target_1.json": lf_lottie_biz_target_1 };
import lf_lottie_biz_target_2 from "../lottie_assets/lottie_biz_target_2.json";
export const entries_1_lf_lottie_biz_target_2 = { "lottie_biz_target_2.json": lf_lottie_biz_target_2 };
import lf_lottie_biz_trophy_1 from "../lottie_assets/lottie_biz_trophy_1.json";
export const entries_1_lf_lottie_biz_trophy_1 = { "lottie_biz_trophy_1.json": lf_lottie_biz_trophy_1 };
import lf_lottie_biz_truck_1 from "../lottie_assets/lottie_biz_truck_1.json";
export const entries_1_lf_lottie_biz_truck_1 = { "lottie_biz_truck_1.json": lf_lottie_biz_truck_1 };
import lf_lottie_biz_truck_2 from "../lottie_assets/lottie_biz_truck_2.json";
export const entries_1_lf_lottie_biz_truck_2 = { "lottie_biz_truck_2.json": lf_lottie_biz_truck_2 };
import lf_lottie_biz_wallet_1 from "../lottie_assets/lottie_biz_wallet_1.json";
export const entries_1_lf_lottie_biz_wallet_1 = { "lottie_biz_wallet_1.json": lf_lottie_biz_wallet_1 };
import lf_lottie_biz_wallet_2 from "../lottie_assets/lottie_biz_wallet_2.json";
export const entries_1_lf_lottie_biz_wallet_2 = { "lottie_biz_wallet_2.json": lf_lottie_biz_wallet_2 };
import lf_lottie_biz_wallet_3 from "../lottie_assets/lottie_biz_wallet_3.json";
export const entries_1_lf_lottie_biz_wallet_3 = { "lottie_biz_wallet_3.json": lf_lottie_biz_wallet_3 };
import lf_lottie_biz_wallet_4 from "../lottie_assets/lottie_biz_wallet_4.json";
export const entries_1_lf_lottie_biz_wallet_4 = { "lottie_biz_wallet_4.json": lf_lottie_biz_wallet_4 };
import lf_lottie_edu_book_1 from "../lottie_assets/lottie_edu_book_1.json";
export const entries_1_lf_lottie_edu_book_1 = { "lottie_edu_book_1.json": lf_lottie_edu_book_1 };
import lf_lottie_edu_book_2 from "../lottie_assets/lottie_edu_book_2.json";
export const entries_1_lf_lottie_edu_book_2 = { "lottie_edu_book_2.json": lf_lottie_edu_book_2 };
import lf_lottie_edu_book_3 from "../lottie_assets/lottie_edu_book_3.json";
export const entries_1_lf_lottie_edu_book_3 = { "lottie_edu_book_3.json": lf_lottie_edu_book_3 };
import lf_lottie_edu_pillar_1 from "../lottie_assets/lottie_edu_pillar_1.json";
export const entries_1_lf_lottie_edu_pillar_1 = { "lottie_edu_pillar_1.json": lf_lottie_edu_pillar_1 };
import lf_lottie_edu_pillar_2 from "../lottie_assets/lottie_edu_pillar_2.json";
export const entries_1_lf_lottie_edu_pillar_2 = { "lottie_edu_pillar_2.json": lf_lottie_edu_pillar_2 };
import lf_lottie_edu_scroll_1 from "../lottie_assets/lottie_edu_scroll_1.json";
export const entries_1_lf_lottie_edu_scroll_1 = { "lottie_edu_scroll_1.json": lf_lottie_edu_scroll_1 };
import lf_lottie_edu_scroll_2 from "../lottie_assets/lottie_edu_scroll_2.json";
export const entries_1_lf_lottie_edu_scroll_2 = { "lottie_edu_scroll_2.json": lf_lottie_edu_scroll_2 };
import lf_lottie_edu_shield_1 from "../lottie_assets/lottie_edu_shield_1.json";
export const entries_1_lf_lottie_edu_shield_1 = { "lottie_edu_shield_1.json": lf_lottie_edu_shield_1 };
import lf_lottie_edu_shield_2 from "../lottie_assets/lottie_edu_shield_2.json";
export const entries_1_lf_lottie_edu_shield_2 = { "lottie_edu_shield_2.json": lf_lottie_edu_shield_2 };
import lf_lottie_edu_write_1 from "../lottie_assets/lottie_edu_write_1.json";
export const entries_1_lf_lottie_edu_write_1 = { "lottie_edu_write_1.json": lf_lottie_edu_write_1 };
import lf_lottie_interact_bell_1 from "../lottie_assets/lottie_interact_bell_1.json";
export const entries_1_lf_lottie_interact_bell_1 = { "lottie_interact_bell_1.json": lf_lottie_interact_bell_1 };
