/* eslint-disable */
import lf_checkmark_success from "../lottie_assets/checkmark_success.json";
export const entries_0_lf_checkmark_success = { "checkmark_success.json": lf_checkmark_success };
import lf_flame from "../lottie_assets/flame.json";
export const entries_0_lf_flame = { "flame.json": lf_flame };
import lf_globe from "../lottie_assets/globe.json";
export const entries_0_lf_globe = { "globe.json": lf_globe };
import lf_info from "../lottie_assets/info.json";
export const entries_0_lf_info = { "info.json": lf_info };
import lf_lottie_arrow_arrow_1 from "../lottie_assets/lottie_arrow_arrow_1.json";
export const entries_0_lf_lottie_arrow_arrow_1 = { "lottie_arrow_arrow_1.json": lf_lottie_arrow_arrow_1 };
import lf_lottie_arrow_arrow_2 from "../lottie_assets/lottie_arrow_arrow_2.json";
export const entries_0_lf_lottie_arrow_arrow_2 = { "lottie_arrow_arrow_2.json": lf_lottie_arrow_arrow_2 };
import lf_lottie_arrow_arrow_3 from "../lottie_assets/lottie_arrow_arrow_3.json";
export const entries_0_lf_lottie_arrow_arrow_3 = { "lottie_arrow_arrow_3.json": lf_lottie_arrow_arrow_3 };
import lf_lottie_arrow_arrow_4 from "../lottie_assets/lottie_arrow_arrow_4.json";
export const entries_0_lf_lottie_arrow_arrow_4 = { "lottie_arrow_arrow_4.json": lf_lottie_arrow_arrow_4 };
import lf_lottie_arrow_arrow_5 from "../lottie_assets/lottie_arrow_arrow_5.json";
export const entries_0_lf_lottie_arrow_arrow_5 = { "lottie_arrow_arrow_5.json": lf_lottie_arrow_arrow_5 };
import lf_lottie_arrow_direction_1 from "../lottie_assets/lottie_arrow_direction_1.json";
export const entries_0_lf_lottie_arrow_direction_1 = { "lottie_arrow_direction_1.json": lf_lottie_arrow_direction_1 };
import lf_lottie_arrow_forward_1 from "../lottie_assets/lottie_arrow_forward_1.json";
export const entries_0_lf_lottie_arrow_forward_1 = { "lottie_arrow_forward_1.json": lf_lottie_arrow_forward_1 };
import lf_lottie_arrow_forward_2 from "../lottie_assets/lottie_arrow_forward_2.json";
export const entries_0_lf_lottie_arrow_forward_2 = { "lottie_arrow_forward_2.json": lf_lottie_arrow_forward_2 };
import lf_lottie_arrow_pause_1 from "../lottie_assets/lottie_arrow_pause_1.json";
export const entries_0_lf_lottie_arrow_pause_1 = { "lottie_arrow_pause_1.json": lf_lottie_arrow_pause_1 };
import lf_lottie_arrow_pause_2 from "../lottie_assets/lottie_arrow_pause_2.json";
export const entries_0_lf_lottie_arrow_pause_2 = { "lottie_arrow_pause_2.json": lf_lottie_arrow_pause_2 };
import lf_lottie_arrow_pause_3 from "../lottie_assets/lottie_arrow_pause_3.json";
export const entries_0_lf_lottie_arrow_pause_3 = { "lottie_arrow_pause_3.json": lf_lottie_arrow_pause_3 };
import lf_lottie_arrow_pause_4 from "../lottie_assets/lottie_arrow_pause_4.json";
export const entries_0_lf_lottie_arrow_pause_4 = { "lottie_arrow_pause_4.json": lf_lottie_arrow_pause_4 };
import lf_lottie_arrow_pause_5 from "../lottie_assets/lottie_arrow_pause_5.json";
export const entries_0_lf_lottie_arrow_pause_5 = { "lottie_arrow_pause_5.json": lf_lottie_arrow_pause_5 };
import lf_lottie_arrow_play_1 from "../lottie_assets/lottie_arrow_play_1.json";
export const entries_0_lf_lottie_arrow_play_1 = { "lottie_arrow_play_1.json": lf_lottie_arrow_play_1 };
import lf_lottie_arrow_play_2 from "../lottie_assets/lottie_arrow_play_2.json";
export const entries_0_lf_lottie_arrow_play_2 = { "lottie_arrow_play_2.json": lf_lottie_arrow_play_2 };
import lf_lottie_arrow_play_3 from "../lottie_assets/lottie_arrow_play_3.json";
export const entries_0_lf_lottie_arrow_play_3 = { "lottie_arrow_play_3.json": lf_lottie_arrow_play_3 };
import lf_lottie_arrow_play_4 from "../lottie_assets/lottie_arrow_play_4.json";
export const entries_0_lf_lottie_arrow_play_4 = { "lottie_arrow_play_4.json": lf_lottie_arrow_play_4 };
import lf_lottie_arrow_play_5 from "../lottie_assets/lottie_arrow_play_5.json";
export const entries_0_lf_lottie_arrow_play_5 = { "lottie_arrow_play_5.json": lf_lottie_arrow_play_5 };
import lf_lottie_arrow_prev_1 from "../lottie_assets/lottie_arrow_prev_1.json";
export const entries_0_lf_lottie_arrow_prev_1 = { "lottie_arrow_prev_1.json": lf_lottie_arrow_prev_1 };
import lf_lottie_arrow_prev_2 from "../lottie_assets/lottie_arrow_prev_2.json";
export const entries_0_lf_lottie_arrow_prev_2 = { "lottie_arrow_prev_2.json": lf_lottie_arrow_prev_2 };
import lf_lottie_arrow_prev_3 from "../lottie_assets/lottie_arrow_prev_3.json";
export const entries_0_lf_lottie_arrow_prev_3 = { "lottie_arrow_prev_3.json": lf_lottie_arrow_prev_3 };
import lf_lottie_biz_analytics_1 from "../lottie_assets/lottie_biz_analytics_1.json";
export const entries_0_lf_lottie_biz_analytics_1 = { "lottie_biz_analytics_1.json": lf_lottie_biz_analytics_1 };
import lf_lottie_biz_analytics_2 from "../lottie_assets/lottie_biz_analytics_2.json";
export const entries_0_lf_lottie_biz_analytics_2 = { "lottie_biz_analytics_2.json": lf_lottie_biz_analytics_2 };
import lf_lottie_biz_analytics_3 from "../lottie_assets/lottie_biz_analytics_3.json";
export const entries_0_lf_lottie_biz_analytics_3 = { "lottie_biz_analytics_3.json": lf_lottie_biz_analytics_3 };
import lf_lottie_biz_analytics_4 from "../lottie_assets/lottie_biz_analytics_4.json";
export const entries_0_lf_lottie_biz_analytics_4 = { "lottie_biz_analytics_4.json": lf_lottie_biz_analytics_4 };
import lf_lottie_biz_analytics_5 from "../lottie_assets/lottie_biz_analytics_5.json";
export const entries_0_lf_lottie_biz_analytics_5 = { "lottie_biz_analytics_5.json": lf_lottie_biz_analytics_5 };
import lf_lottie_biz_award_1 from "../lottie_assets/lottie_biz_award_1.json";
export const entries_0_lf_lottie_biz_award_1 = { "lottie_biz_award_1.json": lf_lottie_biz_award_1 };
import lf_lottie_biz_award_2 from "../lottie_assets/lottie_biz_award_2.json";
export const entries_0_lf_lottie_biz_award_2 = { "lottie_biz_award_2.json": lf_lottie_biz_award_2 };
import lf_lottie_biz_bag_1 from "../lottie_assets/lottie_biz_bag_1.json";
export const entries_0_lf_lottie_biz_bag_1 = { "lottie_biz_bag_1.json": lf_lottie_biz_bag_1 };
import lf_lottie_biz_bag_2 from "../lottie_assets/lottie_biz_bag_2.json";
export const entries_0_lf_lottie_biz_bag_2 = { "lottie_biz_bag_2.json": lf_lottie_biz_bag_2 };
import lf_lottie_biz_bag_3 from "../lottie_assets/lottie_biz_bag_3.json";
export const entries_0_lf_lottie_biz_bag_3 = { "lottie_biz_bag_3.json": lf_lottie_biz_bag_3 };
import lf_lottie_biz_bag_4 from "../lottie_assets/lottie_biz_bag_4.json";
export const entries_0_lf_lottie_biz_bag_4 = { "lottie_biz_bag_4.json": lf_lottie_biz_bag_4 };
import lf_lottie_biz_box_1 from "../lottie_assets/lottie_biz_box_1.json";
export const entries_0_lf_lottie_biz_box_1 = { "lottie_biz_box_1.json": lf_lottie_biz_box_1 };
import lf_lottie_biz_box_2 from "../lottie_assets/lottie_biz_box_2.json";
export const entries_0_lf_lottie_biz_box_2 = { "lottie_biz_box_2.json": lf_lottie_biz_box_2 };
import lf_lottie_biz_box_3 from "../lottie_assets/lottie_biz_box_3.json";
export const entries_0_lf_lottie_biz_box_3 = { "lottie_biz_box_3.json": lf_lottie_biz_box_3 };
import lf_lottie_biz_box_4 from "../lottie_assets/lottie_biz_box_4.json";
export const entries_0_lf_lottie_biz_box_4 = { "lottie_biz_box_4.json": lf_lottie_biz_box_4 };
import lf_lottie_biz_box_5 from "../lottie_assets/lottie_biz_box_5.json";
export const entries_0_lf_lottie_biz_box_5 = { "lottie_biz_box_5.json": lf_lottie_biz_box_5 };
import lf_lottie_biz_card_1 from "../lottie_assets/lottie_biz_card_1.json";
export const entries_0_lf_lottie_biz_card_1 = { "lottie_biz_card_1.json": lf_lottie_biz_card_1 };
import lf_lottie_biz_card_2 from "../lottie_assets/lottie_biz_card_2.json";
export const entries_0_lf_lottie_biz_card_2 = { "lottie_biz_card_2.json": lf_lottie_biz_card_2 };
import lf_lottie_biz_card_3 from "../lottie_assets/lottie_biz_card_3.json";
export const entries_0_lf_lottie_biz_card_3 = { "lottie_biz_card_3.json": lf_lottie_biz_card_3 };
import lf_lottie_biz_cart_1 from "../lottie_assets/lottie_biz_cart_1.json";
export const entries_0_lf_lottie_biz_cart_1 = { "lottie_biz_cart_1.json": lf_lottie_biz_cart_1 };
import lf_lottie_biz_cart_2 from "../lottie_assets/lottie_biz_cart_2.json";
export const entries_0_lf_lottie_biz_cart_2 = { "lottie_biz_cart_2.json": lf_lottie_biz_cart_2 };
import lf_lottie_biz_cart_3 from "../lottie_assets/lottie_biz_cart_3.json";
export const entries_0_lf_lottie_biz_cart_3 = { "lottie_biz_cart_3.json": lf_lottie_biz_cart_3 };
import lf_lottie_biz_chart_1 from "../lottie_assets/lottie_biz_chart_1.json";
export const entries_0_lf_lottie_biz_chart_1 = { "lottie_biz_chart_1.json": lf_lottie_biz_chart_1 };
